// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Thermostat

#ifndef UI_SCREENTTL_H
#define UI_SCREENTTL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenTTL
extern void ui_ScreenTTL_screen_init(void);
extern void ui_ScreenTTL_screen_destroy(void);
extern lv_obj_t * ui_ScreenTTL;
extern lv_obj_t * ui_TextAreaTTL;
extern lv_obj_t * ui_ButtonTTLStart;
extern lv_obj_t * ui_LabelTTLStart;
extern lv_obj_t * ui_ButtonTTLStop;
extern lv_obj_t * ui_LabelTTLStop;
extern lv_obj_t * ui_ButtonTTLSetting;
extern lv_obj_t * ui_LabelTTLSetting;
extern lv_obj_t * ui_ButtonTTLExit;
extern lv_obj_t * ui_LabelTTLExit;
extern lv_obj_t * ui_SwitchTTL1;
extern lv_obj_t * ui_LabelTTL1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenTTL;
extern lv_obj_t * uic_TextAreaTTL;
extern lv_obj_t * uic_ButtonTTLStart;
extern lv_obj_t * uic_LabelTTLStart;
extern lv_obj_t * uic_ButtonTTLStop;
extern lv_obj_t * uic_LabelTTLStop;
extern lv_obj_t * uic_ButtonTTLSetting;
extern lv_obj_t * uic_LabelTTLSetting;
extern lv_obj_t * uic_ButtonTTLExit;
extern lv_obj_t * uic_LabelTTLExit;
extern lv_obj_t * uic_SwitchTTL1;
extern lv_obj_t * uic_LabelTTL1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

