// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Thermostat

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_LabelTTLSettingTitle;
extern lv_obj_t * ui_ContainerTTLSetting2;
extern lv_obj_t * ui_PanelTTLSetting2;
extern lv_obj_t * ui_LabelTTLSettingBaudrate;
extern lv_obj_t * ui_DropdownTTLSettingBaudrate;
extern lv_obj_t * ui_PanelTTLSetting1;
extern lv_obj_t * ui_LabelTTLSettingDatabits;
extern lv_obj_t * ui_DropdownTTLSettingDatabits;
extern lv_obj_t * ui_PanelTTLSetting3;
extern lv_obj_t * ui_LabelTTLSettingParity;
extern lv_obj_t * ui_DropdownTTLSettingParity;
extern lv_obj_t * ui_PanelTTLSetting4;
extern lv_obj_t * ui_LabelTTLSettingStopbits;
extern lv_obj_t * ui_DropdownTTLSettingStopbits;
extern lv_obj_t * ui_PanelTTLSetting5;
extern lv_obj_t * ui_ButtonTTLSettingsApply;
extern lv_obj_t * ui_LabelTTLSetting10;
extern lv_obj_t * ui_ButtonTTLSettingsBack;
extern lv_obj_t * ui_LabelTTLSetting11;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenSettings;
extern lv_obj_t * uic_LabelTTLSettingTitle;
extern lv_obj_t * uic_ContainerTTLSetting2;
extern lv_obj_t * uic_PanelTTLSetting2;
extern lv_obj_t * uic_LabelTTLSettingBaudrate;
extern lv_obj_t * uic_DropdownTTLSettingBaudrate;
extern lv_obj_t * uic_PanelTTLSetting1;
extern lv_obj_t * uic_LabelTTLSettingDatabits;
extern lv_obj_t * uic_DropdownTTLSettingDatabits;
extern lv_obj_t * uic_PanelTTLSetting3;
extern lv_obj_t * uic_LabelTTLSettingParity;
extern lv_obj_t * uic_DropdownTTLSettingParity;
extern lv_obj_t * uic_PanelTTLSetting4;
extern lv_obj_t * uic_LabelTTLSettingStopbits;
extern lv_obj_t * uic_DropdownTTLSettingStopbits;
extern lv_obj_t * uic_PanelTTLSetting5;
extern lv_obj_t * uic_ButtonTTLSettingsApply;
extern lv_obj_t * uic_LabelTTLSetting10;
extern lv_obj_t * uic_ButtonTTLSettingsBack;
extern lv_obj_t * uic_LabelTTLSetting11;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

