// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Thermostat

#include "../ui.h"

lv_obj_t * uic_LabelTTL1;
lv_obj_t * uic_SwitchTTL1;
lv_obj_t * uic_LabelTTLExit;
lv_obj_t * uic_ButtonTTLExit;
lv_obj_t * uic_LabelTTLSetting;
lv_obj_t * uic_ButtonTTLSetting;
lv_obj_t * uic_LabelTTLStop;
lv_obj_t * uic_ButtonTTLStop;
lv_obj_t * uic_LabelTTLStart;
lv_obj_t * uic_ButtonTTLStart;
lv_obj_t * uic_TextAreaTTL;
lv_obj_t * uic_ScreenTTL;
lv_obj_t * ui_ScreenTTL = NULL;
lv_obj_t * ui_TextAreaTTL = NULL;
lv_obj_t * ui_ButtonTTLStart = NULL;
lv_obj_t * ui_LabelTTLStart = NULL;
lv_obj_t * ui_ButtonTTLStop = NULL;
lv_obj_t * ui_LabelTTLStop = NULL;
lv_obj_t * ui_ButtonTTLSetting = NULL;
lv_obj_t * ui_LabelTTLSetting = NULL;
lv_obj_t * ui_ButtonTTLExit = NULL;
lv_obj_t * ui_LabelTTLExit = NULL;
lv_obj_t * ui_SwitchTTL1 = NULL;
lv_obj_t * ui_LabelTTL1 = NULL;
// event funtions

// build funtions

void ui_ScreenTTL_screen_init(void)
{
    ui_ScreenTTL = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTTL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenTTL, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenTTL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenTTL, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaTTL = lv_textarea_create(ui_ScreenTTL);
    lv_obj_set_width(ui_TextAreaTTL, 467);
    lv_obj_set_height(ui_TextAreaTTL, 655);
    lv_obj_set_x(ui_TextAreaTTL, -1);
    lv_obj_set_y(ui_TextAreaTTL, -47);
    lv_obj_set_align(ui_TextAreaTTL, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaTTL, "Placeholder...");

    ui_ButtonTTLStart = lv_btn_create(ui_ScreenTTL);
    lv_obj_set_width(ui_ButtonTTLStart, 64);
    lv_obj_set_height(ui_ButtonTTLStart, 50);
    lv_obj_set_x(ui_ButtonTTLStart, -201);
    lv_obj_set_y(ui_ButtonTTLStart, 324);
    lv_obj_set_align(ui_ButtonTTLStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTTLStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTTLStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTTLStart = lv_label_create(ui_ButtonTTLStart);
    lv_obj_set_width(ui_LabelTTLStart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTTLStart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTTLStart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTTLStart, "START");

    ui_ButtonTTLStop = lv_btn_create(ui_ScreenTTL);
    lv_obj_set_width(ui_ButtonTTLStop, 65);
    lv_obj_set_height(ui_ButtonTTLStop, 50);
    lv_obj_set_x(ui_ButtonTTLStop, -114);
    lv_obj_set_y(ui_ButtonTTLStop, 324);
    lv_obj_set_align(ui_ButtonTTLStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTTLStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTTLStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTTLStop = lv_label_create(ui_ButtonTTLStop);
    lv_obj_set_width(ui_LabelTTLStop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTTLStop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTTLStop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTTLStop, "STOP");

    ui_ButtonTTLSetting = lv_btn_create(ui_ScreenTTL);
    lv_obj_set_width(ui_ButtonTTLSetting, 74);
    lv_obj_set_height(ui_ButtonTTLSetting, 50);
    lv_obj_set_x(ui_ButtonTTLSetting, 86);
    lv_obj_set_y(ui_ButtonTTLSetting, 324);
    lv_obj_set_align(ui_ButtonTTLSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTTLSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTTLSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTTLSetting = lv_label_create(ui_ButtonTTLSetting);
    lv_obj_set_width(ui_LabelTTLSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTTLSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTTLSetting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTTLSetting, "SETTING");

    ui_ButtonTTLExit = lv_btn_create(ui_ScreenTTL);
    lv_obj_set_width(ui_ButtonTTLExit, 63);
    lv_obj_set_height(ui_ButtonTTLExit, 50);
    lv_obj_set_x(ui_ButtonTTLExit, 186);
    lv_obj_set_y(ui_ButtonTTLExit, 324);
    lv_obj_set_align(ui_ButtonTTLExit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTTLExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTTLExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTTLExit = lv_label_create(ui_ButtonTTLExit);
    lv_obj_set_width(ui_LabelTTLExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTTLExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTTLExit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTTLExit, "EXIT");

    ui_SwitchTTL1 = lv_switch_create(ui_ScreenTTL);
    lv_obj_set_width(ui_SwitchTTL1, 109);
    lv_obj_set_height(ui_SwitchTTL1, 50);
    lv_obj_set_x(ui_SwitchTTL1, -17);
    lv_obj_set_y(ui_SwitchTTL1, 324);
    lv_obj_set_align(ui_SwitchTTL1, LV_ALIGN_CENTER);

    ui_LabelTTL1 = lv_label_create(ui_SwitchTTL1);
    lv_obj_set_width(ui_LabelTTL1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTTL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTTL1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTTL1, "TX Heartbeat");

    uic_ScreenTTL = ui_ScreenTTL;
    uic_TextAreaTTL = ui_TextAreaTTL;
    uic_ButtonTTLStart = ui_ButtonTTLStart;
    uic_LabelTTLStart = ui_LabelTTLStart;
    uic_ButtonTTLStop = ui_ButtonTTLStop;
    uic_LabelTTLStop = ui_LabelTTLStop;
    uic_ButtonTTLSetting = ui_ButtonTTLSetting;
    uic_LabelTTLSetting = ui_LabelTTLSetting;
    uic_ButtonTTLExit = ui_ButtonTTLExit;
    uic_LabelTTLExit = ui_LabelTTLExit;
    uic_SwitchTTL1 = ui_SwitchTTL1;
    uic_LabelTTL1 = ui_LabelTTL1;

}

void ui_ScreenTTL_screen_destroy(void)
{
    if(ui_ScreenTTL) lv_obj_del(ui_ScreenTTL);

    // NULL screen variables
    uic_ScreenTTL = NULL;
    ui_ScreenTTL = NULL;
    uic_TextAreaTTL = NULL;
    ui_TextAreaTTL = NULL;
    uic_ButtonTTLStart = NULL;
    ui_ButtonTTLStart = NULL;
    uic_LabelTTLStart = NULL;
    ui_LabelTTLStart = NULL;
    uic_ButtonTTLStop = NULL;
    ui_ButtonTTLStop = NULL;
    uic_LabelTTLStop = NULL;
    ui_LabelTTLStop = NULL;
    uic_ButtonTTLSetting = NULL;
    ui_ButtonTTLSetting = NULL;
    uic_LabelTTLSetting = NULL;
    ui_LabelTTLSetting = NULL;
    uic_ButtonTTLExit = NULL;
    ui_ButtonTTLExit = NULL;
    uic_LabelTTLExit = NULL;
    ui_LabelTTLExit = NULL;
    uic_SwitchTTL1 = NULL;
    ui_SwitchTTL1 = NULL;
    uic_LabelTTL1 = NULL;
    ui_LabelTTL1 = NULL;

}
