// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Thermostat

#include "../ui.h"

lv_obj_t * uic_LabelTTLSetting11;
lv_obj_t * uic_ButtonTTLSettingsBack;
lv_obj_t * uic_LabelTTLSetting10;
lv_obj_t * uic_ButtonTTLSettingsApply;
lv_obj_t * uic_PanelTTLSetting5;
lv_obj_t * uic_DropdownTTLSettingStopbits;
lv_obj_t * uic_LabelTTLSettingStopbits;
lv_obj_t * uic_PanelTTLSetting4;
lv_obj_t * uic_DropdownTTLSettingParity;
lv_obj_t * uic_LabelTTLSettingParity;
lv_obj_t * uic_PanelTTLSetting3;
lv_obj_t * uic_DropdownTTLSettingDatabits;
lv_obj_t * uic_LabelTTLSettingDatabits;
lv_obj_t * uic_PanelTTLSetting1;
lv_obj_t * uic_DropdownTTLSettingBaudrate;
lv_obj_t * uic_LabelTTLSettingBaudrate;
lv_obj_t * uic_PanelTTLSetting2;
lv_obj_t * uic_ContainerTTLSetting2;
lv_obj_t * uic_LabelTTLSettingTitle;
lv_obj_t * uic_ScreenSettings;
lv_obj_t * ui_ScreenSettings = NULL;
lv_obj_t * ui_LabelTTLSettingTitle = NULL;
lv_obj_t * ui_ContainerTTLSetting2 = NULL;
lv_obj_t * ui_PanelTTLSetting2 = NULL;
lv_obj_t * ui_LabelTTLSettingBaudrate = NULL;
lv_obj_t * ui_DropdownTTLSettingBaudrate = NULL;
lv_obj_t * ui_PanelTTLSetting1 = NULL;
lv_obj_t * ui_LabelTTLSettingDatabits = NULL;
lv_obj_t * ui_DropdownTTLSettingDatabits = NULL;
lv_obj_t * ui_PanelTTLSetting3 = NULL;
lv_obj_t * ui_LabelTTLSettingParity = NULL;
lv_obj_t * ui_DropdownTTLSettingParity = NULL;
lv_obj_t * ui_PanelTTLSetting4 = NULL;
lv_obj_t * ui_LabelTTLSettingStopbits = NULL;
lv_obj_t * ui_DropdownTTLSettingStopbits = NULL;
lv_obj_t * ui_PanelTTLSetting5 = NULL;
lv_obj_t * ui_ButtonTTLSettingsApply = NULL;
lv_obj_t * ui_LabelTTLSetting10 = NULL;
lv_obj_t * ui_ButtonTTLSettingsBack = NULL;
lv_obj_t * ui_LabelTTLSetting11 = NULL;
// event funtions

// build funtions

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTTLSettingTitle = lv_label_create(ui_ScreenSettings);
    lv_obj_set_width(ui_LabelTTLSettingTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTTLSettingTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTTLSettingTitle, -1);
    lv_obj_set_y(ui_LabelTTLSettingTitle, -352);
    lv_obj_set_align(ui_LabelTTLSettingTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTTLSettingTitle, "Serial Port Configureation");

    ui_ContainerTTLSetting2 = lv_obj_create(ui_ScreenSettings);
    lv_obj_remove_style_all(ui_ContainerTTLSetting2);
    lv_obj_set_width(ui_ContainerTTLSetting2, 453);
    lv_obj_set_height(ui_ContainerTTLSetting2, 677);
    lv_obj_set_x(ui_ContainerTTLSetting2, -1);
    lv_obj_set_y(ui_ContainerTTLSetting2, 0);
    lv_obj_set_align(ui_ContainerTTLSetting2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerTTLSetting2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerTTLSetting2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerTTLSetting2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelTTLSetting2 = lv_obj_create(ui_ContainerTTLSetting2);
    lv_obj_set_width(ui_PanelTTLSetting2, 450);
    lv_obj_set_height(ui_PanelTTLSetting2, 54);
    lv_obj_set_align(ui_PanelTTLSetting2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTTLSetting2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelTTLSetting2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTTLSetting2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTTLSettingBaudrate = lv_label_create(ui_PanelTTLSetting2);
    lv_obj_set_width(ui_LabelTTLSettingBaudrate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTTLSettingBaudrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTTLSettingBaudrate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTTLSettingBaudrate, "Baud Rate:");

    ui_DropdownTTLSettingBaudrate = lv_dropdown_create(ui_PanelTTLSetting2);
    lv_dropdown_set_options(ui_DropdownTTLSettingBaudrate,
                            "4800\n9600\n19200\n38400\n57600\n115200\n230400\n460800\n1500000");
    lv_obj_set_width(ui_DropdownTTLSettingBaudrate, 221);
    lv_obj_set_height(ui_DropdownTTLSettingBaudrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownTTLSettingBaudrate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownTTLSettingBaudrate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PanelTTLSetting1 = lv_obj_create(ui_ContainerTTLSetting2);
    lv_obj_set_width(ui_PanelTTLSetting1, 450);
    lv_obj_set_height(ui_PanelTTLSetting1, 54);
    lv_obj_set_align(ui_PanelTTLSetting1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTTLSetting1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelTTLSetting1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTTLSetting1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTTLSettingDatabits = lv_label_create(ui_PanelTTLSetting1);
    lv_obj_set_width(ui_LabelTTLSettingDatabits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTTLSettingDatabits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTTLSettingDatabits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTTLSettingDatabits, "Data Bits:");

    ui_DropdownTTLSettingDatabits = lv_dropdown_create(ui_PanelTTLSetting1);
    lv_dropdown_set_options(ui_DropdownTTLSettingDatabits, "5\n6\n7\n8\n");
    lv_obj_set_width(ui_DropdownTTLSettingDatabits, 219);
    lv_obj_set_height(ui_DropdownTTLSettingDatabits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownTTLSettingDatabits, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownTTLSettingDatabits, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PanelTTLSetting3 = lv_obj_create(ui_ContainerTTLSetting2);
    lv_obj_set_width(ui_PanelTTLSetting3, 450);
    lv_obj_set_height(ui_PanelTTLSetting3, 54);
    lv_obj_set_align(ui_PanelTTLSetting3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTTLSetting3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelTTLSetting3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTTLSetting3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTTLSettingParity = lv_label_create(ui_PanelTTLSetting3);
    lv_obj_set_width(ui_LabelTTLSettingParity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTTLSettingParity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTTLSettingParity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTTLSettingParity, "Parity:");

    ui_DropdownTTLSettingParity = lv_dropdown_create(ui_PanelTTLSetting3);
    lv_dropdown_set_options(ui_DropdownTTLSettingParity, "None\nEven\nOdd\n");
    lv_obj_set_width(ui_DropdownTTLSettingParity, 205);
    lv_obj_set_height(ui_DropdownTTLSettingParity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownTTLSettingParity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownTTLSettingParity, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PanelTTLSetting4 = lv_obj_create(ui_ContainerTTLSetting2);
    lv_obj_set_width(ui_PanelTTLSetting4, 450);
    lv_obj_set_height(ui_PanelTTLSetting4, 54);
    lv_obj_set_align(ui_PanelTTLSetting4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTTLSetting4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelTTLSetting4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTTLSetting4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTTLSettingStopbits = lv_label_create(ui_PanelTTLSetting4);
    lv_obj_set_width(ui_LabelTTLSettingStopbits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTTLSettingStopbits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTTLSettingStopbits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTTLSettingStopbits, "Stop Bits:");

    ui_DropdownTTLSettingStopbits = lv_dropdown_create(ui_PanelTTLSetting4);
    lv_dropdown_set_options(ui_DropdownTTLSettingStopbits, "1\n1.5\n2\n");
    lv_obj_set_width(ui_DropdownTTLSettingStopbits, 213);
    lv_obj_set_height(ui_DropdownTTLSettingStopbits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownTTLSettingStopbits, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownTTLSettingStopbits, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PanelTTLSetting5 = lv_obj_create(ui_ContainerTTLSetting2);
    lv_obj_set_width(ui_PanelTTLSetting5, 450);
    lv_obj_set_height(ui_PanelTTLSetting5, 54);
    lv_obj_set_x(ui_PanelTTLSetting5, -2);
    lv_obj_set_y(ui_PanelTTLSetting5, 66);
    lv_obj_set_align(ui_PanelTTLSetting5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTTLSetting5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelTTLSetting5, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTTLSetting5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonTTLSettingsApply = lv_btn_create(ui_PanelTTLSetting5);
    lv_obj_set_width(ui_ButtonTTLSettingsApply, 100);
    lv_obj_set_height(ui_ButtonTTLSettingsApply, 50);
    lv_obj_set_align(ui_ButtonTTLSettingsApply, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTTLSettingsApply, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTTLSettingsApply, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTTLSetting10 = lv_label_create(ui_ButtonTTLSettingsApply);
    lv_obj_set_width(ui_LabelTTLSetting10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTTLSetting10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTTLSetting10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTTLSetting10, "APPLY");

    ui_ButtonTTLSettingsBack = lv_btn_create(ui_PanelTTLSetting5);
    lv_obj_set_width(ui_ButtonTTLSettingsBack, 100);
    lv_obj_set_height(ui_ButtonTTLSettingsBack, 50);
    lv_obj_set_align(ui_ButtonTTLSettingsBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTTLSettingsBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonTTLSettingsBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTTLSetting11 = lv_label_create(ui_ButtonTTLSettingsBack);
    lv_obj_set_width(ui_LabelTTLSetting11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTTLSetting11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTTLSetting11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTTLSetting11, "BACK");

    uic_ScreenSettings = ui_ScreenSettings;
    uic_LabelTTLSettingTitle = ui_LabelTTLSettingTitle;
    uic_ContainerTTLSetting2 = ui_ContainerTTLSetting2;
    uic_PanelTTLSetting2 = ui_PanelTTLSetting2;
    uic_LabelTTLSettingBaudrate = ui_LabelTTLSettingBaudrate;
    uic_DropdownTTLSettingBaudrate = ui_DropdownTTLSettingBaudrate;
    uic_PanelTTLSetting1 = ui_PanelTTLSetting1;
    uic_LabelTTLSettingDatabits = ui_LabelTTLSettingDatabits;
    uic_DropdownTTLSettingDatabits = ui_DropdownTTLSettingDatabits;
    uic_PanelTTLSetting3 = ui_PanelTTLSetting3;
    uic_LabelTTLSettingParity = ui_LabelTTLSettingParity;
    uic_DropdownTTLSettingParity = ui_DropdownTTLSettingParity;
    uic_PanelTTLSetting4 = ui_PanelTTLSetting4;
    uic_LabelTTLSettingStopbits = ui_LabelTTLSettingStopbits;
    uic_DropdownTTLSettingStopbits = ui_DropdownTTLSettingStopbits;
    uic_PanelTTLSetting5 = ui_PanelTTLSetting5;
    uic_ButtonTTLSettingsApply = ui_ButtonTTLSettingsApply;
    uic_LabelTTLSetting10 = ui_LabelTTLSetting10;
    uic_ButtonTTLSettingsBack = ui_ButtonTTLSettingsBack;
    uic_LabelTTLSetting11 = ui_LabelTTLSetting11;

}

void ui_ScreenSettings_screen_destroy(void)
{
    if(ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

    // NULL screen variables
    uic_ScreenSettings = NULL;
    ui_ScreenSettings = NULL;
    uic_LabelTTLSettingTitle = NULL;
    ui_LabelTTLSettingTitle = NULL;
    uic_ContainerTTLSetting2 = NULL;
    ui_ContainerTTLSetting2 = NULL;
    uic_PanelTTLSetting2 = NULL;
    ui_PanelTTLSetting2 = NULL;
    uic_LabelTTLSettingBaudrate = NULL;
    ui_LabelTTLSettingBaudrate = NULL;
    uic_DropdownTTLSettingBaudrate = NULL;
    ui_DropdownTTLSettingBaudrate = NULL;
    uic_PanelTTLSetting1 = NULL;
    ui_PanelTTLSetting1 = NULL;
    uic_LabelTTLSettingDatabits = NULL;
    ui_LabelTTLSettingDatabits = NULL;
    uic_DropdownTTLSettingDatabits = NULL;
    ui_DropdownTTLSettingDatabits = NULL;
    uic_PanelTTLSetting3 = NULL;
    ui_PanelTTLSetting3 = NULL;
    uic_LabelTTLSettingParity = NULL;
    ui_LabelTTLSettingParity = NULL;
    uic_DropdownTTLSettingParity = NULL;
    ui_DropdownTTLSettingParity = NULL;
    uic_PanelTTLSetting4 = NULL;
    ui_PanelTTLSetting4 = NULL;
    uic_LabelTTLSettingStopbits = NULL;
    ui_LabelTTLSettingStopbits = NULL;
    uic_DropdownTTLSettingStopbits = NULL;
    ui_DropdownTTLSettingStopbits = NULL;
    uic_PanelTTLSetting5 = NULL;
    ui_PanelTTLSetting5 = NULL;
    uic_ButtonTTLSettingsApply = NULL;
    ui_ButtonTTLSettingsApply = NULL;
    uic_LabelTTLSetting10 = NULL;
    ui_LabelTTLSetting10 = NULL;
    uic_ButtonTTLSettingsBack = NULL;
    ui_ButtonTTLSettingsBack = NULL;
    uic_LabelTTLSetting11 = NULL;
    ui_LabelTTLSetting11 = NULL;

}
