// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: PowerController

#include "../ui.h"

lv_obj_t * uic_LabelSleepSwitch;
lv_obj_t * uic_SwitchSleep;
lv_obj_t * uic_LabelKeyLockSwtich;
lv_obj_t * uic_SwitchKeyLock;
lv_obj_t * uic_LabelBeepSwitch;
lv_obj_t * uic_SwitchBeep;
lv_obj_t * uic_ContainerSwitch;
lv_obj_t * uic_LabelVoltageInputValue;
lv_obj_t * uic_LabelCurrentSetSign;
lv_obj_t * uic_PanelCurrentSetSign;
lv_obj_t * uic_LabelCurrentSetValue;
lv_obj_t * uic_PanelCurrentSetValue;
lv_obj_t * uic_ContainerCurrentSet;
lv_obj_t * uic_PanelVoltageSetSign;
lv_obj_t * uic_LabelVoltageSetValue;
lv_obj_t * uic_PanelVoltageSetValue;
lv_obj_t * uic_ContainerVoltageSet;
lv_obj_t * uic_LabelADJApply;
lv_obj_t * uic_ButtonADJApply;
lv_obj_t * uic_PanelApplySET;
lv_obj_t * uic_TextAreaADJCurrent;
lv_obj_t * uic_PanelADJCurrentValue;
lv_obj_t * uic_LabelADJCurrent;
lv_obj_t * uic_PanelADJCurrentLabel;
lv_obj_t * uic_ContainerAdjustCurrent;
lv_obj_t * uic_LabelSettings;
lv_obj_t * uic_ButtonSettings;
lv_obj_t * uic_LabelSwitchON;
lv_obj_t * uic_SwitchPower;
lv_obj_t * uic_LabelSwitchOFF;
lv_obj_t * uic_TextAreaADJVoltage;
lv_obj_t * uic_PanelADJVoltageValue;
lv_obj_t * uic_LabelADJVoltage;
lv_obj_t * uic_PanelADJVoltageLabel;
lv_obj_t * uic_ContainerAdjustVoltage;
lv_obj_t * uic_Label12V5A;
lv_obj_t * uic_Button12V5A;
lv_obj_t * uic_Label12V3A;
lv_obj_t * uic_Button12V3A;
lv_obj_t * uic_Container12V;
lv_obj_t * uic_Label5V5A;
lv_obj_t * uic_Button5V5A;
lv_obj_t * uic_Label5V3A;
lv_obj_t * uic_Button5V3A;
lv_obj_t * uic_Container5V;
lv_obj_t * uic_Label3V35A;
lv_obj_t * uic_Button3V35A;
lv_obj_t * uic_Label3V33A;
lv_obj_t * uic_Button3V33A;
lv_obj_t * uic_Container3V3;
lv_obj_t * uic_LabelPowerSign;
lv_obj_t * uic_PanelPowerSign;
lv_obj_t * uic_LabelPowerValue;
lv_obj_t * uic_PanelPowerValue;
lv_obj_t * uic_LabelPower;
lv_obj_t * uic_PanelPower;
lv_obj_t * uic_ContainerPower;
lv_obj_t * uic_LabelCurrentSign;
lv_obj_t * uic_PanelCurrentSign;
lv_obj_t * uic_LabelCurrentValue;
lv_obj_t * uic_PanelCurrentValue;
lv_obj_t * uic_LabelCurrent;
lv_obj_t * uic_PanelCurrentLabel;
lv_obj_t * uic_ContainerCurrent;
lv_obj_t * uic_LabelVoltageSign;
lv_obj_t * uic_PanelVoltageSign;
lv_obj_t * uic_LabelVoltageValue;
lv_obj_t * uic_PanelVoltageValue;
lv_obj_t * uic_LabelVoltage;
lv_obj_t * uic_PanelVoltageLabel;
lv_obj_t * uic_ContainerVoltage;
lv_obj_t * uic_PowerController;
lv_obj_t * ui_PowerController = NULL;
lv_obj_t * ui_ContainerVoltage = NULL;
lv_obj_t * ui_PanelVoltageLabel = NULL;
lv_obj_t * ui_LabelVoltage = NULL;
lv_obj_t * ui_PanelVoltageValue = NULL;
lv_obj_t * ui_LabelVoltageValue = NULL;
lv_obj_t * ui_PanelVoltageSign = NULL;
lv_obj_t * ui_LabelVoltageSign = NULL;
lv_obj_t * ui_ContainerCurrent = NULL;
lv_obj_t * ui_PanelCurrentLabel = NULL;
lv_obj_t * ui_LabelCurrent = NULL;
lv_obj_t * ui_PanelCurrentValue = NULL;
lv_obj_t * ui_LabelCurrentValue = NULL;
lv_obj_t * ui_PanelCurrentSign = NULL;
lv_obj_t * ui_LabelCurrentSign = NULL;
lv_obj_t * ui_ContainerPower = NULL;
lv_obj_t * ui_PanelPower = NULL;
lv_obj_t * ui_LabelPower = NULL;
lv_obj_t * ui_PanelPowerValue = NULL;
lv_obj_t * ui_LabelPowerValue = NULL;
lv_obj_t * ui_PanelPowerSign = NULL;
lv_obj_t * ui_LabelPowerSign = NULL;
lv_obj_t * ui_Container3V3 = NULL;
lv_obj_t * ui_Button3V33A = NULL;
lv_obj_t * ui_Label3V33A = NULL;
lv_obj_t * ui_Button3V35A = NULL;
lv_obj_t * ui_Label3V35A = NULL;
lv_obj_t * ui_Container5V = NULL;
lv_obj_t * ui_Button5V3A = NULL;
lv_obj_t * ui_Label5V3A = NULL;
lv_obj_t * ui_Button5V5A = NULL;
lv_obj_t * ui_Label5V5A = NULL;
lv_obj_t * ui_Container12V = NULL;
lv_obj_t * ui_Button12V3A = NULL;
lv_obj_t * ui_Label12V3A = NULL;
lv_obj_t * ui_Button12V5A = NULL;
lv_obj_t * ui_Label12V5A = NULL;
lv_obj_t * ui_ContainerAdjustVoltage = NULL;
lv_obj_t * ui_PanelADJVoltageLabel = NULL;
lv_obj_t * ui_LabelADJVoltage = NULL;
lv_obj_t * ui_PanelADJVoltageValue = NULL;
lv_obj_t * ui_TextAreaADJVoltage = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_LabelSwitchOFF = NULL;
lv_obj_t * ui_SwitchPower = NULL;
lv_obj_t * ui_LabelSwitchON = NULL;
lv_obj_t * ui_ButtonSettings = NULL;
lv_obj_t * ui_LabelSettings = NULL;
lv_obj_t * ui_ContainerAdjustCurrent = NULL;
lv_obj_t * ui_PanelADJCurrentLabel = NULL;
lv_obj_t * ui_LabelADJCurrent = NULL;
lv_obj_t * ui_PanelADJCurrentValue = NULL;
lv_obj_t * ui_TextAreaADJCurrent = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_PanelApplySET = NULL;
lv_obj_t * ui_ButtonADJApply = NULL;
lv_obj_t * ui_LabelADJApply = NULL;
lv_obj_t * ui_ContainerVoltageSet = NULL;
lv_obj_t * ui_PanelVoltageSetValue = NULL;
lv_obj_t * ui_LabelVoltageSetValue = NULL;
lv_obj_t * ui_PanelVoltageSetSign = NULL;
lv_obj_t * ui_LabelVoltageSign1 = NULL;
lv_obj_t * ui_ContainerCurrentSet = NULL;
lv_obj_t * ui_PanelCurrentSetValue = NULL;
lv_obj_t * ui_LabelCurrentSetValue = NULL;
lv_obj_t * ui_PanelCurrentSetSign = NULL;
lv_obj_t * ui_LabelCurrentSetSign = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Panel15 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_ContainerVoltage1 = NULL;
lv_obj_t * ui_PanelVoltageLabel1 = NULL;
lv_obj_t * ui_LabelVoltage1 = NULL;
lv_obj_t * ui_PanelVoltageValue1 = NULL;
lv_obj_t * ui_LabelVoltageInputValue = NULL;
lv_obj_t * ui_PanelVoltageSign1 = NULL;
lv_obj_t * ui_LabelVoltageSign2 = NULL;
lv_obj_t * ui_ContainerSwitch = NULL;
lv_obj_t * ui_SwitchBeep = NULL;
lv_obj_t * ui_LabelBeepSwitch = NULL;
lv_obj_t * ui_SwitchKeyLock = NULL;
lv_obj_t * ui_LabelKeyLockSwtich = NULL;
lv_obj_t * ui_SwitchSleep = NULL;
lv_obj_t * ui_LabelSleepSwitch = NULL;
lv_obj_t * ui_Keyboard3 = NULL;
// event funtions

// build funtions

void ui_PowerController_screen_init(void)
{
    ui_PowerController = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PowerController, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PowerController, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PowerController, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PowerController, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerVoltage = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_ContainerVoltage);
    lv_obj_set_width(ui_ContainerVoltage, 470);
    lv_obj_set_height(ui_ContainerVoltage, 52);
    lv_obj_set_x(ui_ContainerVoltage, -2);
    lv_obj_set_y(ui_ContainerVoltage, -350);
    lv_obj_set_align(ui_ContainerVoltage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerVoltage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerVoltage, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerVoltage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelVoltageLabel = lv_obj_create(ui_ContainerVoltage);
    lv_obj_set_width(ui_PanelVoltageLabel, 153);
    lv_obj_set_height(ui_PanelVoltageLabel, 50);
    lv_obj_set_x(ui_PanelVoltageLabel, -168);
    lv_obj_set_y(ui_PanelVoltageLabel, -350);
    lv_obj_set_align(ui_PanelVoltageLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelVoltageLabel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelVoltageLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVoltageLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelVoltage = lv_label_create(ui_PanelVoltageLabel);
    lv_obj_set_width(ui_LabelVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVoltage, 6);
    lv_obj_set_y(ui_LabelVoltage, -1);
    lv_obj_set_align(ui_LabelVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVoltage, "VOLTAGE");
    lv_obj_set_style_text_color(ui_LabelVoltage, lv_color_hex(0x138B04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVoltage, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelVoltageValue = lv_obj_create(ui_ContainerVoltage);
    lv_obj_set_width(ui_PanelVoltageValue, 258);
    lv_obj_set_height(ui_PanelVoltageValue, 50);
    lv_obj_set_x(ui_PanelVoltageValue, -22);
    lv_obj_set_y(ui_PanelVoltageValue, -353);
    lv_obj_set_align(ui_PanelVoltageValue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelVoltageValue, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelVoltageValue, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVoltageValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelVoltageValue = lv_label_create(ui_PanelVoltageValue);
    lv_obj_set_width(ui_LabelVoltageValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVoltageValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVoltageValue, 2);
    lv_obj_set_y(ui_LabelVoltageValue, -1);
    lv_obj_set_align(ui_LabelVoltageValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVoltageValue, "00.00");
    lv_obj_set_style_text_color(ui_LabelVoltageValue, lv_color_hex(0x138B04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVoltageValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVoltageValue, &ui_font_JetBrainsMono48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelVoltageSign = lv_obj_create(ui_ContainerVoltage);
    lv_obj_set_width(ui_PanelVoltageSign, 34);
    lv_obj_set_height(ui_PanelVoltageSign, 50);
    lv_obj_set_x(ui_PanelVoltageSign, 140);
    lv_obj_set_y(ui_PanelVoltageSign, -351);
    lv_obj_set_align(ui_PanelVoltageSign, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVoltageSign, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelVoltageSign = lv_label_create(ui_PanelVoltageSign);
    lv_obj_set_width(ui_LabelVoltageSign, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVoltageSign, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelVoltageSign, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVoltageSign, "V");
    lv_obj_set_style_text_color(ui_LabelVoltageSign, lv_color_hex(0x138B04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVoltageSign, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVoltageSign, &ui_font_JetBrainsMono36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCurrent = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_ContainerCurrent);
    lv_obj_set_width(ui_ContainerCurrent, 469);
    lv_obj_set_height(ui_ContainerCurrent, 52);
    lv_obj_set_x(ui_ContainerCurrent, -2);
    lv_obj_set_y(ui_ContainerCurrent, -289);
    lv_obj_set_align(ui_ContainerCurrent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerCurrent, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerCurrent, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerCurrent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelCurrentLabel = lv_obj_create(ui_ContainerCurrent);
    lv_obj_set_width(ui_PanelCurrentLabel, 155);
    lv_obj_set_height(ui_PanelCurrentLabel, 50);
    lv_obj_set_x(ui_PanelCurrentLabel, -111);
    lv_obj_set_y(ui_PanelCurrentLabel, -31);
    lv_obj_set_align(ui_PanelCurrentLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelCurrentLabel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelCurrentLabel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCurrentLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCurrent = lv_label_create(ui_PanelCurrentLabel);
    lv_obj_set_width(ui_LabelCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCurrent, 2);
    lv_obj_set_y(ui_LabelCurrent, 4);
    lv_obj_set_align(ui_LabelCurrent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelCurrent, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelCurrent, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelCurrent, "CURRENT");
    lv_obj_set_style_text_color(ui_LabelCurrent, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurrent, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCurrentValue = lv_obj_create(ui_ContainerCurrent);
    lv_obj_set_width(ui_PanelCurrentValue, 261);
    lv_obj_set_height(ui_PanelCurrentValue, 50);
    lv_obj_set_x(ui_PanelCurrentValue, -106);
    lv_obj_set_y(ui_PanelCurrentValue, 62);
    lv_obj_set_align(ui_PanelCurrentValue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelCurrentValue, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelCurrentValue, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCurrentValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCurrentValue = lv_label_create(ui_PanelCurrentValue);
    lv_obj_set_width(ui_LabelCurrentValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurrentValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCurrentValue, -1);
    lv_obj_set_y(ui_LabelCurrentValue, 3);
    lv_obj_set_align(ui_LabelCurrentValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCurrentValue, "0.000");
    lv_obj_set_style_text_color(ui_LabelCurrentValue, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCurrentValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurrentValue, &ui_font_JetBrainsMono48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCurrentSign = lv_obj_create(ui_ContainerCurrent);
    lv_obj_set_width(ui_PanelCurrentSign, 33);
    lv_obj_set_height(ui_PanelCurrentSign, 50);
    lv_obj_set_x(ui_PanelCurrentSign, -100);
    lv_obj_set_y(ui_PanelCurrentSign, 165);
    lv_obj_set_align(ui_PanelCurrentSign, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCurrentSign, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCurrentSign = lv_label_create(ui_PanelCurrentSign);
    lv_obj_set_width(ui_LabelCurrentSign, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurrentSign, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCurrentSign, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCurrentSign, "A");
    lv_obj_set_style_text_color(ui_LabelCurrentSign, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCurrentSign, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurrentSign, &ui_font_JetBrainsMono36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerPower = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_ContainerPower);
    lv_obj_set_width(ui_ContainerPower, 474);
    lv_obj_set_height(ui_ContainerPower, 55);
    lv_obj_set_x(ui_ContainerPower, 0);
    lv_obj_set_y(ui_ContainerPower, -222);
    lv_obj_set_align(ui_ContainerPower, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerPower, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerPower, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerPower, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelPower = lv_obj_create(ui_ContainerPower);
    lv_obj_set_width(ui_PanelPower, 153);
    lv_obj_set_height(ui_PanelPower, 50);
    lv_obj_set_x(ui_PanelPower, -163);
    lv_obj_set_y(ui_PanelPower, -74);
    lv_obj_set_align(ui_PanelPower, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPower, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelPower, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPower, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPower = lv_label_create(ui_PanelPower);
    lv_obj_set_width(ui_LabelPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPower, 2);
    lv_obj_set_y(ui_LabelPower, 2);
    lv_obj_set_align(ui_LabelPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPower, "POWER");
    lv_obj_set_style_text_color(ui_LabelPower, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPower, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPowerValue = lv_obj_create(ui_ContainerPower);
    lv_obj_set_width(ui_PanelPowerValue, 265);
    lv_obj_set_height(ui_PanelPowerValue, 53);
    lv_obj_set_x(ui_PanelPowerValue, -158);
    lv_obj_set_y(ui_PanelPowerValue, 22);
    lv_obj_set_align(ui_PanelPowerValue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPowerValue, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelPowerValue, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPowerValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPowerValue = lv_label_create(ui_PanelPowerValue);
    lv_obj_set_width(ui_LabelPowerValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPowerValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPowerValue, -4);
    lv_obj_set_y(ui_LabelPowerValue, -4);
    lv_obj_set_align(ui_LabelPowerValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPowerValue, "00.00");
    lv_obj_set_style_text_color(ui_LabelPowerValue, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPowerValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPowerValue, &ui_font_JetBrainsMono48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPowerSign = lv_obj_create(ui_ContainerPower);
    lv_obj_set_width(ui_PanelPowerSign, 36);
    lv_obj_set_height(ui_PanelPowerSign, 50);
    lv_obj_set_x(ui_PanelPowerSign, -146);
    lv_obj_set_y(ui_PanelPowerSign, 137);
    lv_obj_set_align(ui_PanelPowerSign, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPowerSign, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelPowerSign, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPowerSign, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPowerSign = lv_label_create(ui_PanelPowerSign);
    lv_obj_set_width(ui_LabelPowerSign, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPowerSign, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPowerSign, -3);
    lv_obj_set_y(ui_LabelPowerSign, -5);
    lv_obj_set_align(ui_LabelPowerSign, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPowerSign, "W");
    lv_obj_set_style_text_color(ui_LabelPowerSign, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPowerSign, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPowerSign, &ui_font_JetBrainsMono36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3V3 = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_Container3V3);
    lv_obj_set_width(ui_Container3V3, 88);
    lv_obj_set_height(ui_Container3V3, 155);
    lv_obj_set_x(ui_Container3V3, -186);
    lv_obj_set_y(ui_Container3V3, -111);
    lv_obj_set_align(ui_Container3V3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3V3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container3V3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3V3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3V33A = lv_btn_create(ui_Container3V3);
    lv_obj_set_width(ui_Button3V33A, 86);
    lv_obj_set_height(ui_Button3V33A, 52);
    lv_obj_set_x(ui_Button3V33A, -1);
    lv_obj_set_y(ui_Button3V33A, -18);
    lv_obj_set_align(ui_Button3V33A, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button3V33A, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button3V33A, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3V33A, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3V33A, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3V33A = lv_label_create(ui_Button3V33A);
    lv_obj_set_width(ui_Label3V33A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3V33A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3V33A, 0);
    lv_obj_set_y(ui_Label3V33A, 5);
    lv_obj_set_align(ui_Label3V33A, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3V33A, "3V3 3A");
    lv_obj_set_style_text_font(ui_Label3V33A, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3V35A = lv_btn_create(ui_Container3V3);
    lv_obj_set_width(ui_Button3V35A, 86);
    lv_obj_set_height(ui_Button3V35A, 52);
    lv_obj_set_x(ui_Button3V35A, -3);
    lv_obj_set_y(ui_Button3V35A, 92);
    lv_obj_set_align(ui_Button3V35A, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button3V35A, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button3V35A, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3V35A, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3V35A, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3V35A = lv_label_create(ui_Button3V35A);
    lv_obj_set_width(ui_Label3V35A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3V35A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3V35A, 1);
    lv_obj_set_y(ui_Label3V35A, -2);
    lv_obj_set_align(ui_Label3V35A, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3V35A, "3V3 5A");
    lv_obj_set_style_text_font(ui_Label3V35A, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5V = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_Container5V);
    lv_obj_set_width(ui_Container5V, 88);
    lv_obj_set_height(ui_Container5V, 155);
    lv_obj_set_x(ui_Container5V, -83);
    lv_obj_set_y(ui_Container5V, -110);
    lv_obj_set_align(ui_Container5V, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5V, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container5V, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5V, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5V3A = lv_btn_create(ui_Container5V);
    lv_obj_set_width(ui_Button5V3A, 86);
    lv_obj_set_height(ui_Button5V3A, 52);
    lv_obj_set_x(ui_Button5V3A, 4);
    lv_obj_set_y(ui_Button5V3A, 28);
    lv_obj_set_align(ui_Button5V3A, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button5V3A, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button5V3A, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5V3A, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5V3A, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5V3A = lv_label_create(ui_Button5V3A);
    lv_obj_set_width(ui_Label5V3A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5V3A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5V3A, 0);
    lv_obj_set_y(ui_Label5V3A, 3);
    lv_obj_set_align(ui_Label5V3A, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5V3A, "5V 3A");
    lv_obj_set_style_text_font(ui_Label5V3A, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5V5A = lv_btn_create(ui_Container5V);
    lv_obj_set_width(ui_Button5V5A, 86);
    lv_obj_set_height(ui_Button5V5A, 52);
    lv_obj_set_x(ui_Button5V5A, -1);
    lv_obj_set_y(ui_Button5V5A, 135);
    lv_obj_set_align(ui_Button5V5A, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button5V5A, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button5V5A, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5V5A, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5V5A, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5V5A = lv_label_create(ui_Button5V5A);
    lv_obj_set_width(ui_Label5V5A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5V5A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5V5A, 1);
    lv_obj_set_y(ui_Label5V5A, 2);
    lv_obj_set_align(ui_Label5V5A, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5V5A, "5V 5A");
    lv_obj_set_style_text_font(ui_Label5V5A, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12V = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_Container12V);
    lv_obj_set_width(ui_Container12V, 88);
    lv_obj_set_height(ui_Container12V, 155);
    lv_obj_set_x(ui_Container12V, 17);
    lv_obj_set_y(ui_Container12V, -109);
    lv_obj_set_align(ui_Container12V, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container12V, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container12V, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container12V, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button12V3A = lv_btn_create(ui_Container12V);
    lv_obj_set_width(ui_Button12V3A, 86);
    lv_obj_set_height(ui_Button12V3A, 56);
    lv_obj_set_x(ui_Button12V3A, 156);
    lv_obj_set_y(ui_Button12V3A, 9);
    lv_obj_set_align(ui_Button12V3A, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button12V3A, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button12V3A, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12V3A, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12V3A, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12V3A = lv_label_create(ui_Button12V3A);
    lv_obj_set_width(ui_Label12V3A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12V3A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12V3A, -1);
    lv_obj_set_y(ui_Label12V3A, 5);
    lv_obj_set_align(ui_Label12V3A, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12V3A, "12V 3A");
    lv_obj_set_style_text_font(ui_Label12V3A, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12V5A = lv_btn_create(ui_Container12V);
    lv_obj_set_width(ui_Button12V5A, 86);
    lv_obj_set_height(ui_Button12V5A, 52);
    lv_obj_set_x(ui_Button12V5A, 158);
    lv_obj_set_y(ui_Button12V5A, 130);
    lv_obj_set_align(ui_Button12V5A, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button12V5A, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button12V5A, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12V5A, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12V5A, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12V5A = lv_label_create(ui_Button12V5A);
    lv_obj_set_width(ui_Label12V5A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12V5A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12V5A, 6);
    lv_obj_set_y(ui_Label12V5A, 2);
    lv_obj_set_align(ui_Label12V5A, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12V5A, "12V 5A");
    lv_obj_set_style_text_font(ui_Label12V5A, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerAdjustVoltage = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_ContainerAdjustVoltage);
    lv_obj_set_width(ui_ContainerAdjustVoltage, 353);
    lv_obj_set_height(ui_ContainerAdjustVoltage, 59);
    lv_obj_set_x(ui_ContainerAdjustVoltage, -61);
    lv_obj_set_y(ui_ContainerAdjustVoltage, 172);
    lv_obj_set_align(ui_ContainerAdjustVoltage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerAdjustVoltage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerAdjustVoltage, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerAdjustVoltage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelADJVoltageLabel = lv_obj_create(ui_ContainerAdjustVoltage);
    lv_obj_set_width(ui_PanelADJVoltageLabel, 161);
    lv_obj_set_height(ui_PanelADJVoltageLabel, 52);
    lv_obj_set_x(ui_PanelADJVoltageLabel, -161);
    lv_obj_set_y(ui_PanelADJVoltageLabel, 2);
    lv_obj_set_align(ui_PanelADJVoltageLabel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelADJVoltageLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelADJVoltage = lv_label_create(ui_PanelADJVoltageLabel);
    lv_obj_set_width(ui_LabelADJVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelADJVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelADJVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelADJVoltage, "ADJ VOLTAGE");
    lv_obj_set_style_text_color(ui_LabelADJVoltage, lv_color_hex(0xD3650F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelADJVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelADJVoltage, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelADJVoltageValue = lv_obj_create(ui_ContainerAdjustVoltage);
    lv_obj_set_width(ui_PanelADJVoltageValue, 167);
    lv_obj_set_height(ui_PanelADJVoltageValue, 50);
    lv_obj_set_x(ui_PanelADJVoltageValue, 17);
    lv_obj_set_y(ui_PanelADJVoltageValue, 3);
    lv_obj_set_align(ui_PanelADJVoltageValue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelADJVoltageValue, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelADJVoltageValue, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelADJVoltageValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextAreaADJVoltage = lv_textarea_create(ui_PanelADJVoltageValue);
    lv_obj_set_width(ui_TextAreaADJVoltage, 167);
    lv_obj_set_height(ui_TextAreaADJVoltage, LV_SIZE_CONTENT);    /// 65
    lv_obj_set_x(ui_TextAreaADJVoltage, -57);
    lv_obj_set_y(ui_TextAreaADJVoltage, 323);
    lv_obj_set_align(ui_TextAreaADJVoltage, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaADJVoltage, "00.00");
    lv_textarea_set_one_line(ui_TextAreaADJVoltage, true);
    lv_obj_set_style_text_color(ui_TextAreaADJVoltage, lv_color_hex(0xD3650F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaADJVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextAreaADJVoltage, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaADJVoltage, &ui_font_JetBrainsMono36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 460);
    lv_obj_set_height(ui_Container4, 63);
    lv_obj_set_x(ui_Container4, 1);
    lv_obj_set_y(ui_Container4, 329);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSwitchOFF = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_LabelSwitchOFF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSwitchOFF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSwitchOFF, -123);
    lv_obj_set_y(ui_LabelSwitchOFF, 358);
    lv_obj_set_align(ui_LabelSwitchOFF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchOFF, "OFF");
    lv_obj_set_style_text_color(ui_LabelSwitchOFF, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchOFF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSwitchOFF, &ui_font_JetBrainsMono36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchPower = lv_switch_create(ui_Container4);
    lv_obj_set_width(ui_SwitchPower, 127);
    lv_obj_set_height(ui_SwitchPower, 50);
    lv_obj_set_x(ui_SwitchPower, 24);
    lv_obj_set_y(ui_SwitchPower, 356);
    lv_obj_set_align(ui_SwitchPower, LV_ALIGN_CENTER);

    ui_LabelSwitchON = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_LabelSwitchON, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSwitchON, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSwitchON, 182);
    lv_obj_set_y(ui_LabelSwitchON, 359);
    lv_obj_set_align(ui_LabelSwitchON, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchON, "ON");
    lv_obj_set_style_text_color(ui_LabelSwitchON, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSwitchON, &ui_font_JetBrainsMono36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSettings = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_ButtonSettings, 137);
    lv_obj_set_height(ui_ButtonSettings, 70);
    lv_obj_set_x(ui_ButtonSettings, 135);
    lv_obj_set_y(ui_ButtonSettings, 364);
    lv_obj_set_align(ui_ButtonSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSettings = lv_label_create(ui_ButtonSettings);
    lv_obj_set_width(ui_LabelSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSettings, "SETTINGS");
    lv_obj_set_style_text_font(ui_LabelSettings, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerAdjustCurrent = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_ContainerAdjustCurrent);
    lv_obj_set_width(ui_ContainerAdjustCurrent, 350);
    lv_obj_set_height(ui_ContainerAdjustCurrent, 50);
    lv_obj_set_x(ui_ContainerAdjustCurrent, -59);
    lv_obj_set_y(ui_ContainerAdjustCurrent, 240);
    lv_obj_set_align(ui_ContainerAdjustCurrent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerAdjustCurrent, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerAdjustCurrent, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerAdjustCurrent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelADJCurrentLabel = lv_obj_create(ui_ContainerAdjustCurrent);
    lv_obj_set_width(ui_PanelADJCurrentLabel, 161);
    lv_obj_set_height(ui_PanelADJCurrentLabel, 50);
    lv_obj_set_x(ui_PanelADJCurrentLabel, 164);
    lv_obj_set_y(ui_PanelADJCurrentLabel, 11);
    lv_obj_set_align(ui_PanelADJCurrentLabel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelADJCurrentLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelADJCurrent = lv_label_create(ui_PanelADJCurrentLabel);
    lv_obj_set_width(ui_LabelADJCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelADJCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelADJCurrent, -2);
    lv_obj_set_y(ui_LabelADJCurrent, 1);
    lv_obj_set_align(ui_LabelADJCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelADJCurrent, "ADJ CURRENT");
    lv_obj_set_style_text_color(ui_LabelADJCurrent, lv_color_hex(0xD3650F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelADJCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelADJCurrent, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelADJCurrentValue = lv_obj_create(ui_ContainerAdjustCurrent);
    lv_obj_set_width(ui_PanelADJCurrentValue, 167);
    lv_obj_set_height(ui_PanelADJCurrentValue, 50);
    lv_obj_set_x(ui_PanelADJCurrentValue, 75);
    lv_obj_set_y(ui_PanelADJCurrentValue, 328);
    lv_obj_set_align(ui_PanelADJCurrentValue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelADJCurrentValue, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelADJCurrentValue, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelADJCurrentValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextAreaADJCurrent = lv_textarea_create(ui_PanelADJCurrentValue);
    lv_obj_set_width(ui_TextAreaADJCurrent, 177);
    lv_obj_set_height(ui_TextAreaADJCurrent, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextAreaADJCurrent, 125);
    lv_obj_set_y(ui_TextAreaADJCurrent, 338);
    lv_obj_set_align(ui_TextAreaADJCurrent, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaADJCurrent, "0.000");
    lv_textarea_set_one_line(ui_TextAreaADJCurrent, true);
    lv_obj_set_style_text_color(ui_TextAreaADJCurrent, lv_color_hex(0xD3650F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextAreaADJCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextAreaADJCurrent, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaADJCurrent, &ui_font_JetBrainsMono36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 100);
    lv_obj_set_height(ui_Container6, 115);
    lv_obj_set_x(ui_Container6, 175);
    lv_obj_set_y(ui_Container6, 204);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelApplySET = lv_obj_create(ui_Container6);
    lv_obj_set_width(ui_PanelApplySET, 95);
    lv_obj_set_height(ui_PanelApplySET, 115);
    lv_obj_set_x(ui_PanelApplySET, 306);
    lv_obj_set_y(ui_PanelApplySET, 443);
    lv_obj_set_align(ui_PanelApplySET, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelApplySET, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelApplySET, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelApplySET, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonADJApply = lv_btn_create(ui_PanelApplySET);
    lv_obj_set_width(ui_ButtonADJApply, 93);
    lv_obj_set_height(ui_ButtonADJApply, 113);
    lv_obj_set_x(ui_ButtonADJApply, 72);
    lv_obj_set_y(ui_ButtonADJApply, 347);
    lv_obj_set_align(ui_ButtonADJApply, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ButtonADJApply, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ButtonADJApply, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonADJApply, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonADJApply, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelADJApply = lv_label_create(ui_ButtonADJApply);
    lv_obj_set_width(ui_LabelADJApply, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelADJApply, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelADJApply, 21);
    lv_obj_set_y(ui_LabelADJApply, 366);
    lv_obj_set_align(ui_LabelADJApply, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelADJApply, "SET");
    lv_obj_set_style_text_font(ui_LabelADJApply, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerVoltageSet = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_ContainerVoltageSet);
    lv_obj_set_width(ui_ContainerVoltageSet, 300);
    lv_obj_set_height(ui_ContainerVoltageSet, 52);
    lv_obj_set_x(ui_ContainerVoltageSet, 78);
    lv_obj_set_y(ui_ContainerVoltageSet, -2);
    lv_obj_set_align(ui_ContainerVoltageSet, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerVoltageSet, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerVoltageSet, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerVoltageSet, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelVoltageSetValue = lv_obj_create(ui_ContainerVoltageSet);
    lv_obj_set_width(ui_PanelVoltageSetValue, 260);
    lv_obj_set_height(ui_PanelVoltageSetValue, 50);
    lv_obj_set_x(ui_PanelVoltageSetValue, -22);
    lv_obj_set_y(ui_PanelVoltageSetValue, -353);
    lv_obj_set_align(ui_PanelVoltageSetValue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelVoltageSetValue, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelVoltageSetValue, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVoltageSetValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelVoltageSetValue = lv_label_create(ui_PanelVoltageSetValue);
    lv_obj_set_width(ui_LabelVoltageSetValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVoltageSetValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVoltageSetValue, 2);
    lv_obj_set_y(ui_LabelVoltageSetValue, -1);
    lv_obj_set_align(ui_LabelVoltageSetValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVoltageSetValue, "00.00");
    lv_obj_set_style_text_color(ui_LabelVoltageSetValue, lv_color_hex(0x138B04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVoltageSetValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVoltageSetValue, &ui_font_JetBrainsMono48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelVoltageSetSign = lv_obj_create(ui_ContainerVoltageSet);
    lv_obj_set_width(ui_PanelVoltageSetSign, 34);
    lv_obj_set_height(ui_PanelVoltageSetSign, 50);
    lv_obj_set_x(ui_PanelVoltageSetSign, 140);
    lv_obj_set_y(ui_PanelVoltageSetSign, -351);
    lv_obj_set_align(ui_PanelVoltageSetSign, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVoltageSetSign, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelVoltageSign1 = lv_label_create(ui_PanelVoltageSetSign);
    lv_obj_set_width(ui_LabelVoltageSign1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVoltageSign1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelVoltageSign1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVoltageSign1, "V");
    lv_obj_set_style_text_color(ui_LabelVoltageSign1, lv_color_hex(0x138B04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVoltageSign1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVoltageSign1, &ui_font_JetBrainsMono36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCurrentSet = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_ContainerCurrentSet);
    lv_obj_set_width(ui_ContainerCurrentSet, 299);
    lv_obj_set_height(ui_ContainerCurrentSet, 52);
    lv_obj_set_x(ui_ContainerCurrentSet, 76);
    lv_obj_set_y(ui_ContainerCurrentSet, 53);
    lv_obj_set_align(ui_ContainerCurrentSet, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerCurrentSet, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerCurrentSet, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerCurrentSet, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelCurrentSetValue = lv_obj_create(ui_ContainerCurrentSet);
    lv_obj_set_width(ui_PanelCurrentSetValue, 261);
    lv_obj_set_height(ui_PanelCurrentSetValue, 50);
    lv_obj_set_x(ui_PanelCurrentSetValue, -106);
    lv_obj_set_y(ui_PanelCurrentSetValue, 62);
    lv_obj_set_align(ui_PanelCurrentSetValue, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelCurrentSetValue, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelCurrentSetValue, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCurrentSetValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCurrentSetValue = lv_label_create(ui_PanelCurrentSetValue);
    lv_obj_set_width(ui_LabelCurrentSetValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurrentSetValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCurrentSetValue, -1);
    lv_obj_set_y(ui_LabelCurrentSetValue, 3);
    lv_obj_set_align(ui_LabelCurrentSetValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCurrentSetValue, "0.000");
    lv_obj_set_style_text_color(ui_LabelCurrentSetValue, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCurrentSetValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurrentSetValue, &ui_font_JetBrainsMono48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCurrentSetSign = lv_obj_create(ui_ContainerCurrentSet);
    lv_obj_set_width(ui_PanelCurrentSetSign, 33);
    lv_obj_set_height(ui_PanelCurrentSetSign, 50);
    lv_obj_set_x(ui_PanelCurrentSetSign, -100);
    lv_obj_set_y(ui_PanelCurrentSetSign, 165);
    lv_obj_set_align(ui_PanelCurrentSetSign, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCurrentSetSign, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCurrentSetSign = lv_label_create(ui_PanelCurrentSetSign);
    lv_obj_set_width(ui_LabelCurrentSetSign, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurrentSetSign, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCurrentSetSign, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCurrentSetSign, "A");
    lv_obj_set_style_text_color(ui_LabelCurrentSetSign, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCurrentSetSign, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurrentSetSign, &ui_font_JetBrainsMono36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 155);
    lv_obj_set_height(ui_Container7, 116);
    lv_obj_set_x(ui_Container7, -154);
    lv_obj_set_y(ui_Container7, 31);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel15 = lv_obj_create(ui_Container7);
    lv_obj_set_width(ui_Panel15, 151);
    lv_obj_set_height(ui_Panel15, 104);
    lv_obj_set_x(ui_Panel15, 8);
    lv_obj_set_y(ui_Panel15, -3);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "SETTED");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_JetBrainsMono36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerVoltage1 = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_ContainerVoltage1);
    lv_obj_set_width(ui_ContainerVoltage1, 470);
    lv_obj_set_height(ui_ContainerVoltage1, 52);
    lv_obj_set_x(ui_ContainerVoltage1, -2);
    lv_obj_set_y(ui_ContainerVoltage1, 114);
    lv_obj_set_align(ui_ContainerVoltage1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerVoltage1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerVoltage1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerVoltage1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelVoltageLabel1 = lv_obj_create(ui_ContainerVoltage1);
    lv_obj_set_width(ui_PanelVoltageLabel1, 153);
    lv_obj_set_height(ui_PanelVoltageLabel1, 50);
    lv_obj_set_x(ui_PanelVoltageLabel1, -168);
    lv_obj_set_y(ui_PanelVoltageLabel1, -350);
    lv_obj_set_align(ui_PanelVoltageLabel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelVoltageLabel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelVoltageLabel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVoltageLabel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelVoltage1 = lv_label_create(ui_PanelVoltageLabel1);
    lv_obj_set_width(ui_LabelVoltage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVoltage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVoltage1, 6);
    lv_obj_set_y(ui_LabelVoltage1, -1);
    lv_obj_set_align(ui_LabelVoltage1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVoltage1, "INPUT");
    lv_obj_set_style_text_color(ui_LabelVoltage1, lv_color_hex(0xC507C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVoltage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVoltage1, &ui_font_JetBrainsMono36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelVoltageValue1 = lv_obj_create(ui_ContainerVoltage1);
    lv_obj_set_width(ui_PanelVoltageValue1, 258);
    lv_obj_set_height(ui_PanelVoltageValue1, 50);
    lv_obj_set_x(ui_PanelVoltageValue1, -25);
    lv_obj_set_y(ui_PanelVoltageValue1, -353);
    lv_obj_set_align(ui_PanelVoltageValue1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelVoltageValue1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelVoltageValue1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVoltageValue1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelVoltageInputValue = lv_label_create(ui_PanelVoltageValue1);
    lv_obj_set_width(ui_LabelVoltageInputValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVoltageInputValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVoltageInputValue, 2);
    lv_obj_set_y(ui_LabelVoltageInputValue, -1);
    lv_obj_set_align(ui_LabelVoltageInputValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVoltageInputValue, "00.00");
    lv_obj_set_style_text_color(ui_LabelVoltageInputValue, lv_color_hex(0xC507C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVoltageInputValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVoltageInputValue, &ui_font_JetBrainsMono48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelVoltageSign1 = lv_obj_create(ui_ContainerVoltage1);
    lv_obj_set_width(ui_PanelVoltageSign1, 36);
    lv_obj_set_height(ui_PanelVoltageSign1, 50);
    lv_obj_set_x(ui_PanelVoltageSign1, 140);
    lv_obj_set_y(ui_PanelVoltageSign1, -351);
    lv_obj_set_align(ui_PanelVoltageSign1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVoltageSign1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelVoltageSign2 = lv_label_create(ui_PanelVoltageSign1);
    lv_obj_set_width(ui_LabelVoltageSign2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVoltageSign2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelVoltageSign2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVoltageSign2, "V");
    lv_obj_set_style_text_color(ui_LabelVoltageSign2, lv_color_hex(0xC507C7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVoltageSign2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVoltageSign2, &ui_font_JetBrainsMono36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSwitch = lv_obj_create(ui_PowerController);
    lv_obj_remove_style_all(ui_ContainerSwitch);
    lv_obj_set_width(ui_ContainerSwitch, 146);
    lv_obj_set_height(ui_ContainerSwitch, 150);
    lv_obj_set_x(ui_ContainerSwitch, 149);
    lv_obj_set_y(ui_ContainerSwitch, -112);
    lv_obj_set_align(ui_ContainerSwitch, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerSwitch, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerSwitch, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerSwitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchBeep = lv_switch_create(ui_ContainerSwitch);
    lv_obj_set_width(ui_SwitchBeep, 138);
    lv_obj_set_height(ui_SwitchBeep, 39);
    lv_obj_set_x(ui_SwitchBeep, 34);
    lv_obj_set_y(ui_SwitchBeep, -38);
    lv_obj_set_align(ui_SwitchBeep, LV_ALIGN_CENTER);

    ui_LabelBeepSwitch = lv_label_create(ui_SwitchBeep);
    lv_obj_set_width(ui_LabelBeepSwitch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBeepSwitch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBeepSwitch, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBeepSwitch, "BEEP");
    lv_obj_set_style_text_font(ui_LabelBeepSwitch, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchKeyLock = lv_switch_create(ui_ContainerSwitch);
    lv_obj_set_width(ui_SwitchKeyLock, 138);
    lv_obj_set_height(ui_SwitchKeyLock, 39);
    lv_obj_set_x(ui_SwitchKeyLock, 34);
    lv_obj_set_y(ui_SwitchKeyLock, -38);
    lv_obj_set_align(ui_SwitchKeyLock, LV_ALIGN_CENTER);

    ui_LabelKeyLockSwtich = lv_label_create(ui_SwitchKeyLock);
    lv_obj_set_width(ui_LabelKeyLockSwtich, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKeyLockSwtich, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelKeyLockSwtich, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKeyLockSwtich, "LOCK");
    lv_obj_set_style_text_font(ui_LabelKeyLockSwtich, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchSleep = lv_switch_create(ui_ContainerSwitch);
    lv_obj_set_width(ui_SwitchSleep, 138);
    lv_obj_set_height(ui_SwitchSleep, 39);
    lv_obj_set_x(ui_SwitchSleep, 34);
    lv_obj_set_y(ui_SwitchSleep, -38);
    lv_obj_set_align(ui_SwitchSleep, LV_ALIGN_CENTER);

    ui_LabelSleepSwitch = lv_label_create(ui_SwitchSleep);
    lv_obj_set_width(ui_LabelSleepSwitch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSleepSwitch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSleepSwitch, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSleepSwitch, "SLEEP");
    lv_obj_set_style_text_font(ui_LabelSleepSwitch, &ui_font_JetBrainsMono24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard3 = lv_keyboard_create(ui_PowerController);
    lv_keyboard_set_mode(ui_Keyboard3, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard3, 300);
    lv_obj_set_height(ui_Keyboard3, 238);
    lv_obj_set_x(ui_Keyboard3, -4);
    lv_obj_set_y(ui_Keyboard3, 19);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    uic_PowerController = ui_PowerController;
    uic_ContainerVoltage = ui_ContainerVoltage;
    uic_PanelVoltageLabel = ui_PanelVoltageLabel;
    uic_LabelVoltage = ui_LabelVoltage;
    uic_PanelVoltageValue = ui_PanelVoltageValue;
    uic_LabelVoltageValue = ui_LabelVoltageValue;
    uic_PanelVoltageSign = ui_PanelVoltageSign;
    uic_LabelVoltageSign = ui_LabelVoltageSign;
    uic_ContainerCurrent = ui_ContainerCurrent;
    uic_PanelCurrentLabel = ui_PanelCurrentLabel;
    uic_LabelCurrent = ui_LabelCurrent;
    uic_PanelCurrentValue = ui_PanelCurrentValue;
    uic_LabelCurrentValue = ui_LabelCurrentValue;
    uic_PanelCurrentSign = ui_PanelCurrentSign;
    uic_LabelCurrentSign = ui_LabelCurrentSign;
    uic_ContainerPower = ui_ContainerPower;
    uic_PanelPower = ui_PanelPower;
    uic_LabelPower = ui_LabelPower;
    uic_PanelPowerValue = ui_PanelPowerValue;
    uic_LabelPowerValue = ui_LabelPowerValue;
    uic_PanelPowerSign = ui_PanelPowerSign;
    uic_LabelPowerSign = ui_LabelPowerSign;
    uic_Container3V3 = ui_Container3V3;
    uic_Button3V33A = ui_Button3V33A;
    uic_Label3V33A = ui_Label3V33A;
    uic_Button3V35A = ui_Button3V35A;
    uic_Label3V35A = ui_Label3V35A;
    uic_Container5V = ui_Container5V;
    uic_Button5V3A = ui_Button5V3A;
    uic_Label5V3A = ui_Label5V3A;
    uic_Button5V5A = ui_Button5V5A;
    uic_Label5V5A = ui_Label5V5A;
    uic_Container12V = ui_Container12V;
    uic_Button12V3A = ui_Button12V3A;
    uic_Label12V3A = ui_Label12V3A;
    uic_Button12V5A = ui_Button12V5A;
    uic_Label12V5A = ui_Label12V5A;
    uic_ContainerAdjustVoltage = ui_ContainerAdjustVoltage;
    uic_PanelADJVoltageLabel = ui_PanelADJVoltageLabel;
    uic_LabelADJVoltage = ui_LabelADJVoltage;
    uic_PanelADJVoltageValue = ui_PanelADJVoltageValue;
    uic_TextAreaADJVoltage = ui_TextAreaADJVoltage;
    uic_LabelSwitchOFF = ui_LabelSwitchOFF;
    uic_SwitchPower = ui_SwitchPower;
    uic_LabelSwitchON = ui_LabelSwitchON;
    uic_ButtonSettings = ui_ButtonSettings;
    uic_LabelSettings = ui_LabelSettings;
    uic_ContainerAdjustCurrent = ui_ContainerAdjustCurrent;
    uic_PanelADJCurrentLabel = ui_PanelADJCurrentLabel;
    uic_LabelADJCurrent = ui_LabelADJCurrent;
    uic_PanelADJCurrentValue = ui_PanelADJCurrentValue;
    uic_TextAreaADJCurrent = ui_TextAreaADJCurrent;
    uic_PanelApplySET = ui_PanelApplySET;
    uic_ButtonADJApply = ui_ButtonADJApply;
    uic_LabelADJApply = ui_LabelADJApply;
    uic_ContainerVoltageSet = ui_ContainerVoltageSet;
    uic_PanelVoltageSetValue = ui_PanelVoltageSetValue;
    uic_LabelVoltageSetValue = ui_LabelVoltageSetValue;
    uic_PanelVoltageSetSign = ui_PanelVoltageSetSign;
    uic_ContainerCurrentSet = ui_ContainerCurrentSet;
    uic_PanelCurrentSetValue = ui_PanelCurrentSetValue;
    uic_LabelCurrentSetValue = ui_LabelCurrentSetValue;
    uic_PanelCurrentSetSign = ui_PanelCurrentSetSign;
    uic_LabelCurrentSetSign = ui_LabelCurrentSetSign;
    uic_LabelVoltageInputValue = ui_LabelVoltageInputValue;
    uic_ContainerSwitch = ui_ContainerSwitch;
    uic_SwitchBeep = ui_SwitchBeep;
    uic_LabelBeepSwitch = ui_LabelBeepSwitch;
    uic_SwitchKeyLock = ui_SwitchKeyLock;
    uic_LabelKeyLockSwtich = ui_LabelKeyLockSwtich;
    uic_SwitchSleep = ui_SwitchSleep;
    uic_LabelSleepSwitch = ui_LabelSleepSwitch;

}

void ui_PowerController_screen_destroy(void)
{
    if(ui_PowerController) lv_obj_del(ui_PowerController);

    // NULL screen variables
    uic_PowerController = NULL;
    ui_PowerController = NULL;
    uic_ContainerVoltage = NULL;
    ui_ContainerVoltage = NULL;
    uic_PanelVoltageLabel = NULL;
    ui_PanelVoltageLabel = NULL;
    uic_LabelVoltage = NULL;
    ui_LabelVoltage = NULL;
    uic_PanelVoltageValue = NULL;
    ui_PanelVoltageValue = NULL;
    uic_LabelVoltageValue = NULL;
    ui_LabelVoltageValue = NULL;
    uic_PanelVoltageSign = NULL;
    ui_PanelVoltageSign = NULL;
    uic_LabelVoltageSign = NULL;
    ui_LabelVoltageSign = NULL;
    uic_ContainerCurrent = NULL;
    ui_ContainerCurrent = NULL;
    uic_PanelCurrentLabel = NULL;
    ui_PanelCurrentLabel = NULL;
    uic_LabelCurrent = NULL;
    ui_LabelCurrent = NULL;
    uic_PanelCurrentValue = NULL;
    ui_PanelCurrentValue = NULL;
    uic_LabelCurrentValue = NULL;
    ui_LabelCurrentValue = NULL;
    uic_PanelCurrentSign = NULL;
    ui_PanelCurrentSign = NULL;
    uic_LabelCurrentSign = NULL;
    ui_LabelCurrentSign = NULL;
    uic_ContainerPower = NULL;
    ui_ContainerPower = NULL;
    uic_PanelPower = NULL;
    ui_PanelPower = NULL;
    uic_LabelPower = NULL;
    ui_LabelPower = NULL;
    uic_PanelPowerValue = NULL;
    ui_PanelPowerValue = NULL;
    uic_LabelPowerValue = NULL;
    ui_LabelPowerValue = NULL;
    uic_PanelPowerSign = NULL;
    ui_PanelPowerSign = NULL;
    uic_LabelPowerSign = NULL;
    ui_LabelPowerSign = NULL;
    uic_Container3V3 = NULL;
    ui_Container3V3 = NULL;
    uic_Button3V33A = NULL;
    ui_Button3V33A = NULL;
    uic_Label3V33A = NULL;
    ui_Label3V33A = NULL;
    uic_Button3V35A = NULL;
    ui_Button3V35A = NULL;
    uic_Label3V35A = NULL;
    ui_Label3V35A = NULL;
    uic_Container5V = NULL;
    ui_Container5V = NULL;
    uic_Button5V3A = NULL;
    ui_Button5V3A = NULL;
    uic_Label5V3A = NULL;
    ui_Label5V3A = NULL;
    uic_Button5V5A = NULL;
    ui_Button5V5A = NULL;
    uic_Label5V5A = NULL;
    ui_Label5V5A = NULL;
    uic_Container12V = NULL;
    ui_Container12V = NULL;
    uic_Button12V3A = NULL;
    ui_Button12V3A = NULL;
    uic_Label12V3A = NULL;
    ui_Label12V3A = NULL;
    uic_Button12V5A = NULL;
    ui_Button12V5A = NULL;
    uic_Label12V5A = NULL;
    ui_Label12V5A = NULL;
    uic_ContainerAdjustVoltage = NULL;
    ui_ContainerAdjustVoltage = NULL;
    uic_PanelADJVoltageLabel = NULL;
    ui_PanelADJVoltageLabel = NULL;
    uic_LabelADJVoltage = NULL;
    ui_LabelADJVoltage = NULL;
    uic_PanelADJVoltageValue = NULL;
    ui_PanelADJVoltageValue = NULL;
    uic_TextAreaADJVoltage = NULL;
    ui_TextAreaADJVoltage = NULL;
    ui_Container4 = NULL;
    uic_LabelSwitchOFF = NULL;
    ui_LabelSwitchOFF = NULL;
    uic_SwitchPower = NULL;
    ui_SwitchPower = NULL;
    uic_LabelSwitchON = NULL;
    ui_LabelSwitchON = NULL;
    uic_ButtonSettings = NULL;
    ui_ButtonSettings = NULL;
    uic_LabelSettings = NULL;
    ui_LabelSettings = NULL;
    uic_ContainerAdjustCurrent = NULL;
    ui_ContainerAdjustCurrent = NULL;
    uic_PanelADJCurrentLabel = NULL;
    ui_PanelADJCurrentLabel = NULL;
    uic_LabelADJCurrent = NULL;
    ui_LabelADJCurrent = NULL;
    uic_PanelADJCurrentValue = NULL;
    ui_PanelADJCurrentValue = NULL;
    uic_TextAreaADJCurrent = NULL;
    ui_TextAreaADJCurrent = NULL;
    ui_Container6 = NULL;
    uic_PanelApplySET = NULL;
    ui_PanelApplySET = NULL;
    uic_ButtonADJApply = NULL;
    ui_ButtonADJApply = NULL;
    uic_LabelADJApply = NULL;
    ui_LabelADJApply = NULL;
    uic_ContainerVoltageSet = NULL;
    ui_ContainerVoltageSet = NULL;
    uic_PanelVoltageSetValue = NULL;
    ui_PanelVoltageSetValue = NULL;
    uic_LabelVoltageSetValue = NULL;
    ui_LabelVoltageSetValue = NULL;
    uic_PanelVoltageSetSign = NULL;
    ui_PanelVoltageSetSign = NULL;
    ui_LabelVoltageSign1 = NULL;
    uic_ContainerCurrentSet = NULL;
    ui_ContainerCurrentSet = NULL;
    uic_PanelCurrentSetValue = NULL;
    ui_PanelCurrentSetValue = NULL;
    uic_LabelCurrentSetValue = NULL;
    ui_LabelCurrentSetValue = NULL;
    uic_PanelCurrentSetSign = NULL;
    ui_PanelCurrentSetSign = NULL;
    uic_LabelCurrentSetSign = NULL;
    ui_LabelCurrentSetSign = NULL;
    ui_Container7 = NULL;
    ui_Panel15 = NULL;
    ui_Label25 = NULL;
    ui_ContainerVoltage1 = NULL;
    ui_PanelVoltageLabel1 = NULL;
    ui_LabelVoltage1 = NULL;
    ui_PanelVoltageValue1 = NULL;
    uic_LabelVoltageInputValue = NULL;
    ui_LabelVoltageInputValue = NULL;
    ui_PanelVoltageSign1 = NULL;
    ui_LabelVoltageSign2 = NULL;
    uic_ContainerSwitch = NULL;
    ui_ContainerSwitch = NULL;
    uic_SwitchBeep = NULL;
    ui_SwitchBeep = NULL;
    uic_LabelBeepSwitch = NULL;
    ui_LabelBeepSwitch = NULL;
    uic_SwitchKeyLock = NULL;
    ui_SwitchKeyLock = NULL;
    uic_LabelKeyLockSwtich = NULL;
    ui_LabelKeyLockSwtich = NULL;
    uic_SwitchSleep = NULL;
    ui_SwitchSleep = NULL;
    uic_LabelSleepSwitch = NULL;
    ui_LabelSleepSwitch = NULL;
    ui_Keyboard3 = NULL;

}
