// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: PowerController

#ifndef UI_POWERCONTROLLER_H
#define UI_POWERCONTROLLER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PowerController
extern void ui_PowerController_screen_init(void);
extern void ui_PowerController_screen_destroy(void);
extern lv_obj_t * ui_PowerController;
extern lv_obj_t * ui_ContainerVoltage;
extern lv_obj_t * ui_PanelVoltageLabel;
extern lv_obj_t * ui_LabelVoltage;
extern lv_obj_t * ui_PanelVoltageValue;
extern lv_obj_t * ui_LabelVoltageValue;
extern lv_obj_t * ui_PanelVoltageSign;
extern lv_obj_t * ui_LabelVoltageSign;
extern lv_obj_t * ui_ContainerCurrent;
extern lv_obj_t * ui_PanelCurrentLabel;
extern lv_obj_t * ui_LabelCurrent;
extern lv_obj_t * ui_PanelCurrentValue;
extern lv_obj_t * ui_LabelCurrentValue;
extern lv_obj_t * ui_PanelCurrentSign;
extern lv_obj_t * ui_LabelCurrentSign;
extern lv_obj_t * ui_ContainerPower;
extern lv_obj_t * ui_PanelPower;
extern lv_obj_t * ui_LabelPower;
extern lv_obj_t * ui_PanelPowerValue;
extern lv_obj_t * ui_LabelPowerValue;
extern lv_obj_t * ui_PanelPowerSign;
extern lv_obj_t * ui_LabelPowerSign;
extern lv_obj_t * ui_Container3V3;
extern lv_obj_t * ui_Button3V33A;
extern lv_obj_t * ui_Label3V33A;
extern lv_obj_t * ui_Button3V35A;
extern lv_obj_t * ui_Label3V35A;
extern lv_obj_t * ui_Container5V;
extern lv_obj_t * ui_Button5V3A;
extern lv_obj_t * ui_Label5V3A;
extern lv_obj_t * ui_Button5V5A;
extern lv_obj_t * ui_Label5V5A;
extern lv_obj_t * ui_Container12V;
extern lv_obj_t * ui_Button12V3A;
extern lv_obj_t * ui_Label12V3A;
extern lv_obj_t * ui_Button12V5A;
extern lv_obj_t * ui_Label12V5A;
extern lv_obj_t * ui_ContainerAdjustVoltage;
extern lv_obj_t * ui_PanelADJVoltageLabel;
extern lv_obj_t * ui_LabelADJVoltage;
extern lv_obj_t * ui_PanelADJVoltageValue;
extern lv_obj_t * ui_TextAreaADJVoltage;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_LabelSwitchOFF;
extern lv_obj_t * ui_SwitchPower;
extern lv_obj_t * ui_LabelSwitchON;
extern lv_obj_t * ui_ButtonSettings;
extern lv_obj_t * ui_LabelSettings;
extern lv_obj_t * ui_ContainerAdjustCurrent;
extern lv_obj_t * ui_PanelADJCurrentLabel;
extern lv_obj_t * ui_LabelADJCurrent;
extern lv_obj_t * ui_PanelADJCurrentValue;
extern lv_obj_t * ui_TextAreaADJCurrent;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_PanelApplySET;
extern lv_obj_t * ui_ButtonADJApply;
extern lv_obj_t * ui_LabelADJApply;
extern lv_obj_t * ui_ContainerVoltageSet;
extern lv_obj_t * ui_PanelVoltageSetValue;
extern lv_obj_t * ui_LabelVoltageSetValue;
extern lv_obj_t * ui_PanelVoltageSetSign;
extern lv_obj_t * ui_LabelVoltageSign1;
extern lv_obj_t * ui_ContainerCurrentSet;
extern lv_obj_t * ui_PanelCurrentSetValue;
extern lv_obj_t * ui_LabelCurrentSetValue;
extern lv_obj_t * ui_PanelCurrentSetSign;
extern lv_obj_t * ui_LabelCurrentSetSign;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_ContainerVoltage1;
extern lv_obj_t * ui_PanelVoltageLabel1;
extern lv_obj_t * ui_LabelVoltage1;
extern lv_obj_t * ui_PanelVoltageValue1;
extern lv_obj_t * ui_LabelVoltageInputValue;
extern lv_obj_t * ui_PanelVoltageSign1;
extern lv_obj_t * ui_LabelVoltageSign2;
extern lv_obj_t * ui_ContainerSwitch;
extern lv_obj_t * ui_SwitchBeep;
extern lv_obj_t * ui_LabelBeepSwitch;
extern lv_obj_t * ui_SwitchKeyLock;
extern lv_obj_t * ui_LabelKeyLockSwtich;
extern lv_obj_t * ui_SwitchSleep;
extern lv_obj_t * ui_LabelSleepSwitch;
extern lv_obj_t * ui_Keyboard3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PowerController;
extern lv_obj_t * uic_ContainerVoltage;
extern lv_obj_t * uic_PanelVoltageLabel;
extern lv_obj_t * uic_LabelVoltage;
extern lv_obj_t * uic_PanelVoltageValue;
extern lv_obj_t * uic_LabelVoltageValue;
extern lv_obj_t * uic_PanelVoltageSign;
extern lv_obj_t * uic_LabelVoltageSign;
extern lv_obj_t * uic_ContainerCurrent;
extern lv_obj_t * uic_PanelCurrentLabel;
extern lv_obj_t * uic_LabelCurrent;
extern lv_obj_t * uic_PanelCurrentValue;
extern lv_obj_t * uic_LabelCurrentValue;
extern lv_obj_t * uic_PanelCurrentSign;
extern lv_obj_t * uic_LabelCurrentSign;
extern lv_obj_t * uic_ContainerPower;
extern lv_obj_t * uic_PanelPower;
extern lv_obj_t * uic_LabelPower;
extern lv_obj_t * uic_PanelPowerValue;
extern lv_obj_t * uic_LabelPowerValue;
extern lv_obj_t * uic_PanelPowerSign;
extern lv_obj_t * uic_LabelPowerSign;
extern lv_obj_t * uic_Container3V3;
extern lv_obj_t * uic_Button3V33A;
extern lv_obj_t * uic_Label3V33A;
extern lv_obj_t * uic_Button3V35A;
extern lv_obj_t * uic_Label3V35A;
extern lv_obj_t * uic_Container5V;
extern lv_obj_t * uic_Button5V3A;
extern lv_obj_t * uic_Label5V3A;
extern lv_obj_t * uic_Button5V5A;
extern lv_obj_t * uic_Label5V5A;
extern lv_obj_t * uic_Container12V;
extern lv_obj_t * uic_Button12V3A;
extern lv_obj_t * uic_Label12V3A;
extern lv_obj_t * uic_Button12V5A;
extern lv_obj_t * uic_Label12V5A;
extern lv_obj_t * uic_ContainerAdjustVoltage;
extern lv_obj_t * uic_PanelADJVoltageLabel;
extern lv_obj_t * uic_LabelADJVoltage;
extern lv_obj_t * uic_PanelADJVoltageValue;
extern lv_obj_t * uic_TextAreaADJVoltage;
extern lv_obj_t * uic_LabelSwitchOFF;
extern lv_obj_t * uic_SwitchPower;
extern lv_obj_t * uic_LabelSwitchON;
extern lv_obj_t * uic_ButtonSettings;
extern lv_obj_t * uic_LabelSettings;
extern lv_obj_t * uic_ContainerAdjustCurrent;
extern lv_obj_t * uic_PanelADJCurrentLabel;
extern lv_obj_t * uic_LabelADJCurrent;
extern lv_obj_t * uic_PanelADJCurrentValue;
extern lv_obj_t * uic_TextAreaADJCurrent;
extern lv_obj_t * uic_PanelApplySET;
extern lv_obj_t * uic_ButtonADJApply;
extern lv_obj_t * uic_LabelADJApply;
extern lv_obj_t * uic_ContainerVoltageSet;
extern lv_obj_t * uic_PanelVoltageSetValue;
extern lv_obj_t * uic_LabelVoltageSetValue;
extern lv_obj_t * uic_PanelVoltageSetSign;
extern lv_obj_t * uic_ContainerCurrentSet;
extern lv_obj_t * uic_PanelCurrentSetValue;
extern lv_obj_t * uic_LabelCurrentSetValue;
extern lv_obj_t * uic_PanelCurrentSetSign;
extern lv_obj_t * uic_LabelCurrentSetSign;
extern lv_obj_t * uic_LabelVoltageInputValue;
extern lv_obj_t * uic_ContainerSwitch;
extern lv_obj_t * uic_SwitchBeep;
extern lv_obj_t * uic_LabelBeepSwitch;
extern lv_obj_t * uic_SwitchKeyLock;
extern lv_obj_t * uic_LabelKeyLockSwtich;
extern lv_obj_t * uic_SwitchSleep;
extern lv_obj_t * uic_LabelSleepSwitch;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

