// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Thermostat

#ifndef _THERMOSTAT_UI_H
#define _THERMOSTAT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "esp_brookesia.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_ScreenUSB.h"
#include "screens/ui_ScreenUSBSettings.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui_usb____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Number);

// UI INIT
void ui_usb_init(void);
void ui_usb_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
