// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Thermostat

#include "../ui.h"

lv_obj_t * uic_LabelUSBBack;
lv_obj_t * uic_ButtonUSBSettingBack;
lv_obj_t * uic_LabelUSBApply;
lv_obj_t * uic_ButtonUSBSettingsApply;
lv_obj_t * uic_PanelUSB6;
lv_obj_t * uic_DropdownUSBStopbits;
lv_obj_t * uic_LabelUSBStopbits;
lv_obj_t * uic_PanelUSB5;
lv_obj_t * uic_DropdownUSBParity;
lv_obj_t * uic_LabelUSBParity;
lv_obj_t * uic_PanelUSB4;
lv_obj_t * uic_DropdownUSBDatabits;
lv_obj_t * uic_LabelUSBDatabits;
lv_obj_t * uic_PanelUSB3;
lv_obj_t * uic_DropdownUSBBaudrate;
lv_obj_t * uic_LabelUSBBaudrate;
lv_obj_t * uic_PanelUSB2;
lv_obj_t * uic_USBContainer2;
lv_obj_t * uic_LabelUSBTitle;
lv_obj_t * uic_ScreenUSBSettings;
lv_obj_t * ui_ScreenUSBSettings = NULL;
lv_obj_t * ui_LabelUSBTitle = NULL;
lv_obj_t * ui_USBContainer2 = NULL;
lv_obj_t * ui_PanelUSB2 = NULL;
lv_obj_t * ui_LabelUSBBaudrate = NULL;
lv_obj_t * ui_DropdownUSBBaudrate = NULL;
lv_obj_t * ui_PanelUSB3 = NULL;
lv_obj_t * ui_LabelUSBDatabits = NULL;
lv_obj_t * ui_DropdownUSBDatabits = NULL;
lv_obj_t * ui_PanelUSB4 = NULL;
lv_obj_t * ui_LabelUSBParity = NULL;
lv_obj_t * ui_DropdownUSBParity = NULL;
lv_obj_t * ui_PanelUSB5 = NULL;
lv_obj_t * ui_LabelUSBStopbits = NULL;
lv_obj_t * ui_DropdownUSBStopbits = NULL;
lv_obj_t * ui_PanelUSB6 = NULL;
lv_obj_t * ui_ButtonUSBSettingsApply = NULL;
lv_obj_t * ui_LabelUSBApply = NULL;
lv_obj_t * ui_ButtonUSBSettingsBack = NULL;
lv_obj_t * ui_LabelUSBBack = NULL;
// event funtions

// build funtions

void ui_ScreenUSBSettings_screen_init(void)
{
    ui_ScreenUSBSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenUSBSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUSBTitle = lv_label_create(ui_ScreenUSBSettings);
    lv_obj_set_width(ui_LabelUSBTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSBTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUSBTitle, -1);
    lv_obj_set_y(ui_LabelUSBTitle, -352);
    lv_obj_set_align(ui_LabelUSBTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSBTitle, "USB Serial Port Configureation");

    ui_USBContainer2 = lv_obj_create(ui_ScreenUSBSettings);
    lv_obj_remove_style_all(ui_USBContainer2);
    lv_obj_set_width(ui_USBContainer2, 453);
    lv_obj_set_height(ui_USBContainer2, 677);
    lv_obj_set_x(ui_USBContainer2, -1);
    lv_obj_set_y(ui_USBContainer2, 0);
    lv_obj_set_align(ui_USBContainer2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_USBContainer2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_USBContainer2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_USBContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelUSB2 = lv_obj_create(ui_USBContainer2);
    lv_obj_set_width(ui_PanelUSB2, 450);
    lv_obj_set_height(ui_PanelUSB2, 54);
    lv_obj_set_align(ui_PanelUSB2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelUSB2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelUSB2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelUSB2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUSBBaudrate = lv_label_create(ui_PanelUSB2);
    lv_obj_set_width(ui_LabelUSBBaudrate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSBBaudrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUSBBaudrate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSBBaudrate, "Baud Rate:");

    ui_DropdownUSBBaudrate = lv_dropdown_create(ui_PanelUSB2);
    lv_dropdown_set_options(ui_DropdownUSBBaudrate, "4800\n9600\n19200\n38400\n57600\n115200\n230400\n460800\n1500000");
    lv_obj_set_width(ui_DropdownUSBBaudrate, 221);
    lv_obj_set_height(ui_DropdownUSBBaudrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownUSBBaudrate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownUSBBaudrate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PanelUSB3 = lv_obj_create(ui_USBContainer2);
    lv_obj_set_width(ui_PanelUSB3, 450);
    lv_obj_set_height(ui_PanelUSB3, 54);
    lv_obj_set_align(ui_PanelUSB3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelUSB3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelUSB3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelUSB3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUSBDatabits = lv_label_create(ui_PanelUSB3);
    lv_obj_set_width(ui_LabelUSBDatabits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSBDatabits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUSBDatabits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSBDatabits, "Data Bits:");

    ui_DropdownUSBDatabits = lv_dropdown_create(ui_PanelUSB3);
    lv_dropdown_set_options(ui_DropdownUSBDatabits, "5\n6\n7\n8\n");
    lv_obj_set_width(ui_DropdownUSBDatabits, 219);
    lv_obj_set_height(ui_DropdownUSBDatabits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownUSBDatabits, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownUSBDatabits, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PanelUSB4 = lv_obj_create(ui_USBContainer2);
    lv_obj_set_width(ui_PanelUSB4, 450);
    lv_obj_set_height(ui_PanelUSB4, 54);
    lv_obj_set_align(ui_PanelUSB4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelUSB4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelUSB4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelUSB4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUSBParity = lv_label_create(ui_PanelUSB4);
    lv_obj_set_width(ui_LabelUSBParity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSBParity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUSBParity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSBParity, "Parity:");

    ui_DropdownUSBParity = lv_dropdown_create(ui_PanelUSB4);
    lv_dropdown_set_options(ui_DropdownUSBParity, "None\nEven\nOdd\n");
    lv_obj_set_width(ui_DropdownUSBParity, 205);
    lv_obj_set_height(ui_DropdownUSBParity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownUSBParity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownUSBParity, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PanelUSB5 = lv_obj_create(ui_USBContainer2);
    lv_obj_set_width(ui_PanelUSB5, 450);
    lv_obj_set_height(ui_PanelUSB5, 54);
    lv_obj_set_align(ui_PanelUSB5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelUSB5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelUSB5, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelUSB5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUSBStopbits = lv_label_create(ui_PanelUSB5);
    lv_obj_set_width(ui_LabelUSBStopbits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSBStopbits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUSBStopbits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSBStopbits, "Stop Bits:");

    ui_DropdownUSBStopbits = lv_dropdown_create(ui_PanelUSB5);
    lv_dropdown_set_options(ui_DropdownUSBStopbits, "1\n1.5\n2\n");
    lv_obj_set_width(ui_DropdownUSBStopbits, 213);
    lv_obj_set_height(ui_DropdownUSBStopbits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownUSBStopbits, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownUSBStopbits, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PanelUSB6 = lv_obj_create(ui_USBContainer2);
    lv_obj_set_width(ui_PanelUSB6, 450);
    lv_obj_set_height(ui_PanelUSB6, 54);
    lv_obj_set_x(ui_PanelUSB6, -2);
    lv_obj_set_y(ui_PanelUSB6, 66);
    lv_obj_set_align(ui_PanelUSB6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelUSB6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelUSB6, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelUSB6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonUSBSettingsApply = lv_btn_create(ui_PanelUSB6);
    lv_obj_set_width(ui_ButtonUSBSettingsApply, 100);
    lv_obj_set_height(ui_ButtonUSBSettingsApply, 50);
    lv_obj_set_align(ui_ButtonUSBSettingsApply, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUSBSettingsApply, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonUSBSettingsApply, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUSBApply = lv_label_create(ui_ButtonUSBSettingsApply);
    lv_obj_set_width(ui_LabelUSBApply, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSBApply, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUSBApply, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSBApply, "APPLY");

    ui_ButtonUSBSettingsBack = lv_btn_create(ui_PanelUSB6);
    lv_obj_set_width(ui_ButtonUSBSettingsBack, 100);
    lv_obj_set_height(ui_ButtonUSBSettingsBack, 50);
    lv_obj_set_align(ui_ButtonUSBSettingsBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUSBSettingsBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonUSBSettingsBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUSBBack = lv_label_create(ui_ButtonUSBSettingsBack);
    lv_obj_set_width(ui_LabelUSBBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSBBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUSBBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSBBack, "BACK");

    uic_ScreenUSBSettings = ui_ScreenUSBSettings;
    uic_LabelUSBTitle = ui_LabelUSBTitle;
    uic_USBContainer2 = ui_USBContainer2;
    uic_PanelUSB2 = ui_PanelUSB2;
    uic_LabelUSBBaudrate = ui_LabelUSBBaudrate;
    uic_DropdownUSBBaudrate = ui_DropdownUSBBaudrate;
    uic_PanelUSB3 = ui_PanelUSB3;
    uic_LabelUSBDatabits = ui_LabelUSBDatabits;
    uic_DropdownUSBDatabits = ui_DropdownUSBDatabits;
    uic_PanelUSB4 = ui_PanelUSB4;
    uic_LabelUSBParity = ui_LabelUSBParity;
    uic_DropdownUSBParity = ui_DropdownUSBParity;
    uic_PanelUSB5 = ui_PanelUSB5;
    uic_LabelUSBStopbits = ui_LabelUSBStopbits;
    uic_DropdownUSBStopbits = ui_DropdownUSBStopbits;
    uic_PanelUSB6 = ui_PanelUSB6;
    uic_ButtonUSBSettingsApply = ui_ButtonUSBSettingsApply;
    uic_LabelUSBApply = ui_LabelUSBApply;
    uic_ButtonUSBSettingBack = ui_ButtonUSBSettingsBack;
    uic_LabelUSBBack = ui_LabelUSBBack;

}

void ui_ScreenUSBSettings_screen_destroy(void)
{
    if(ui_ScreenUSBSettings) lv_obj_del(ui_ScreenUSBSettings);

    // NULL screen variables
    uic_ScreenUSBSettings = NULL;
    ui_ScreenUSBSettings = NULL;
    uic_LabelUSBTitle = NULL;
    ui_LabelUSBTitle = NULL;
    uic_USBContainer2 = NULL;
    ui_USBContainer2 = NULL;
    uic_PanelUSB2 = NULL;
    ui_PanelUSB2 = NULL;
    uic_LabelUSBBaudrate = NULL;
    ui_LabelUSBBaudrate = NULL;
    uic_DropdownUSBBaudrate = NULL;
    ui_DropdownUSBBaudrate = NULL;
    uic_PanelUSB3 = NULL;
    ui_PanelUSB3 = NULL;
    uic_LabelUSBDatabits = NULL;
    ui_LabelUSBDatabits = NULL;
    uic_DropdownUSBDatabits = NULL;
    ui_DropdownUSBDatabits = NULL;
    uic_PanelUSB4 = NULL;
    ui_PanelUSB4 = NULL;
    uic_LabelUSBParity = NULL;
    ui_LabelUSBParity = NULL;
    uic_DropdownUSBParity = NULL;
    ui_DropdownUSBParity = NULL;
    uic_PanelUSB5 = NULL;
    ui_PanelUSB5 = NULL;
    uic_LabelUSBStopbits = NULL;
    ui_LabelUSBStopbits = NULL;
    uic_DropdownUSBStopbits = NULL;
    ui_DropdownUSBStopbits = NULL;
    uic_PanelUSB6 = NULL;
    ui_PanelUSB6 = NULL;
    uic_ButtonUSBSettingsApply = NULL;
    ui_ButtonUSBSettingsApply = NULL;
    uic_LabelUSBApply = NULL;
    ui_LabelUSBApply = NULL;
    uic_ButtonUSBSettingBack = NULL;
    ui_ButtonUSBSettingsBack = NULL;
    uic_LabelUSBBack = NULL;
    ui_LabelUSBBack = NULL;

}
