// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Thermostat

#ifndef UI_SCREENUSB_H
#define UI_SCREENUSB_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenUSB
extern void ui_ScreenUSB_screen_init(void);
extern void ui_ScreenUSB_screen_destroy(void);
extern lv_obj_t * ui_ScreenUSB;
extern lv_obj_t * ui_TextAreaUSB;
extern lv_obj_t * ui_ButtonUSBStart;
extern lv_obj_t * ui_LabelUSBStart;
extern lv_obj_t * ui_ButtonUSBStop;
extern lv_obj_t * ui_LabelUSBStop;
extern lv_obj_t * ui_ButtonUSBSetting;
extern lv_obj_t * ui_LabelUSBSettings;
extern lv_obj_t * ui_ButtonUSBExit;
extern lv_obj_t * ui_LabelUSBExit;
extern lv_obj_t * ui_SwitchUSBHeartbeat;
extern lv_obj_t * ui_LabelUSBHeartbeat;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenUSB;
extern lv_obj_t * uic_TextAreaUSB;
extern lv_obj_t * uic_ButtonUSBStart;
extern lv_obj_t * uic_LabelUSBStart;
extern lv_obj_t * uic_ButtonUSBStop;
extern lv_obj_t * uic_LabelUSBStop;
extern lv_obj_t * uic_ButtonUSBSetting;
extern lv_obj_t * uic_LabelUSBSettings;
extern lv_obj_t * uic_ButtonUSBExit;
extern lv_obj_t * uic_LabelUSBExit;
extern lv_obj_t * uic_SwitchUSBHeartbeat;
extern lv_obj_t * uic_LabelUSBHeartbeat;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

