// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Thermostat

#ifndef UI_SCREENUSBSETTINGS_H
#define UI_SCREENUSBSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenUSBSettings
extern void ui_ScreenUSBSettings_screen_init(void);
extern void ui_ScreenUSBSettings_screen_destroy(void);
extern lv_obj_t * ui_ScreenUSBSettings;
extern lv_obj_t * ui_LabelUSBTitle;
extern lv_obj_t * ui_USBContainer2;
extern lv_obj_t * ui_PanelUSB2;
extern lv_obj_t * ui_LabelUSBBaudrate;
extern lv_obj_t * ui_DropdownUSBBaudrate;
extern lv_obj_t * ui_PanelUSB3;
extern lv_obj_t * ui_LabelUSBDatabits;
extern lv_obj_t * ui_DropdownUSBDatabits;
extern lv_obj_t * ui_PanelUSB4;
extern lv_obj_t * ui_LabelUSBParity;
extern lv_obj_t * ui_DropdownUSBParity;
extern lv_obj_t * ui_PanelUSB5;
extern lv_obj_t * ui_LabelUSBStopbits;
extern lv_obj_t * ui_DropdownUSBStopbits;
extern lv_obj_t * ui_PanelUSB6;
extern lv_obj_t * ui_ButtonUSBSettingsApply;
extern lv_obj_t * ui_LabelUSBApply;
extern lv_obj_t * ui_ButtonUSBSettingsBack;
extern lv_obj_t * ui_LabelUSBBack;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenUSBSettings;
extern lv_obj_t * uic_LabelUSBTitle;
extern lv_obj_t * uic_USBContainer2;
extern lv_obj_t * uic_PanelUSB2;
extern lv_obj_t * uic_LabelUSBBaudrate;
extern lv_obj_t * uic_DropdownUSBBaudrate;
extern lv_obj_t * uic_PanelUSB3;
extern lv_obj_t * uic_LabelUSBDatabits;
extern lv_obj_t * uic_DropdownUSBDatabits;
extern lv_obj_t * uic_PanelUSB4;
extern lv_obj_t * uic_LabelUSBParity;
extern lv_obj_t * uic_DropdownUSBParity;
extern lv_obj_t * uic_PanelUSB5;
extern lv_obj_t * uic_LabelUSBStopbits;
extern lv_obj_t * uic_DropdownUSBStopbits;
extern lv_obj_t * uic_PanelUSB6;
extern lv_obj_t * uic_ButtonUSBSettingsApply;
extern lv_obj_t * uic_LabelUSBApply;
extern lv_obj_t * uic_ButtonUSBSettingBack;
extern lv_obj_t * uic_LabelUSBBack;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

