// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Thermostat

#include "../ui.h"

lv_obj_t * uic_LabelUSBHeartbeat;
lv_obj_t * uic_SwitchUSBHeartbeat;
lv_obj_t * uic_LabelUSBExit;
lv_obj_t * uic_ButtonUSBExit;
lv_obj_t * uic_LabelUSBSettings;
lv_obj_t * uic_ButtonUSBSetting;
lv_obj_t * uic_LabelUSBStop;
lv_obj_t * uic_ButtonUSBStop;
lv_obj_t * uic_LabelUSBStart;
lv_obj_t * uic_ButtonUSBStart;
lv_obj_t * uic_TextAreaUSB;
lv_obj_t * uic_ScreenUSB;
lv_obj_t * ui_ScreenUSB = NULL;
lv_obj_t * ui_TextAreaUSB = NULL;
lv_obj_t * ui_ButtonUSBStart = NULL;
lv_obj_t * ui_LabelUSBStart = NULL;
lv_obj_t * ui_ButtonUSBStop = NULL;
lv_obj_t * ui_LabelUSBStop = NULL;
lv_obj_t * ui_ButtonUSBSetting = NULL;
lv_obj_t * ui_LabelUSBSettings = NULL;
lv_obj_t * ui_ButtonUSBExit = NULL;
lv_obj_t * ui_LabelUSBExit = NULL;
lv_obj_t * ui_SwitchUSBHeartbeat = NULL;
lv_obj_t * ui_LabelUSBHeartbeat = NULL;
// event funtions

// build funtions

void ui_ScreenUSB_screen_init(void)
{
    ui_ScreenUSB = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenUSB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenUSB, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenUSB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenUSB, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaUSB = lv_textarea_create(ui_ScreenUSB);
    lv_obj_set_width(ui_TextAreaUSB, 467);
    lv_obj_set_height(ui_TextAreaUSB, 655);
    lv_obj_set_x(ui_TextAreaUSB, -1);
    lv_obj_set_y(ui_TextAreaUSB, -47);
    lv_obj_set_align(ui_TextAreaUSB, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaUSB, "Placeholder...");

    ui_ButtonUSBStart = lv_btn_create(ui_ScreenUSB);
    lv_obj_set_width(ui_ButtonUSBStart, 70);
    lv_obj_set_height(ui_ButtonUSBStart, 50);
    lv_obj_set_x(ui_ButtonUSBStart, -193);
    lv_obj_set_y(ui_ButtonUSBStart, 324);
    lv_obj_set_align(ui_ButtonUSBStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUSBStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonUSBStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUSBStart = lv_label_create(ui_ButtonUSBStart);
    lv_obj_set_width(ui_LabelUSBStart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSBStart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUSBStart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSBStart, "START");

    ui_ButtonUSBStop = lv_btn_create(ui_ScreenUSB);
    lv_obj_set_width(ui_ButtonUSBStop, 75);
    lv_obj_set_height(ui_ButtonUSBStop, 50);
    lv_obj_set_x(ui_ButtonUSBStop, -114);
    lv_obj_set_y(ui_ButtonUSBStop, 324);
    lv_obj_set_align(ui_ButtonUSBStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUSBStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonUSBStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUSBStop = lv_label_create(ui_ButtonUSBStop);
    lv_obj_set_width(ui_LabelUSBStop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSBStop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUSBStop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSBStop, "STOP");

    ui_ButtonUSBSetting = lv_btn_create(ui_ScreenUSB);
    lv_obj_set_width(ui_ButtonUSBSetting, 80);
    lv_obj_set_height(ui_ButtonUSBSetting, 50);
    lv_obj_set_x(ui_ButtonUSBSetting, 111);
    lv_obj_set_y(ui_ButtonUSBSetting, 324);
    lv_obj_set_align(ui_ButtonUSBSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUSBSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonUSBSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUSBSettings = lv_label_create(ui_ButtonUSBSetting);
    lv_obj_set_width(ui_LabelUSBSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSBSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUSBSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSBSettings, "SETTING");

    ui_ButtonUSBExit = lv_btn_create(ui_ScreenUSB);
    lv_obj_set_width(ui_ButtonUSBExit, 68);
    lv_obj_set_height(ui_ButtonUSBExit, 50);
    lv_obj_set_x(ui_ButtonUSBExit, 193);
    lv_obj_set_y(ui_ButtonUSBExit, 324);
    lv_obj_set_align(ui_ButtonUSBExit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUSBExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonUSBExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUSBExit = lv_label_create(ui_ButtonUSBExit);
    lv_obj_set_width(ui_LabelUSBExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSBExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUSBExit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSBExit, "EXIT");

    ui_SwitchUSBHeartbeat = lv_switch_create(ui_ScreenUSB);
    lv_obj_set_width(ui_SwitchUSBHeartbeat, 121);
    lv_obj_set_height(ui_SwitchUSBHeartbeat, 50);
    lv_obj_set_x(ui_SwitchUSBHeartbeat, -7);
    lv_obj_set_y(ui_SwitchUSBHeartbeat, 324);
    lv_obj_set_align(ui_SwitchUSBHeartbeat, LV_ALIGN_CENTER);

    ui_LabelUSBHeartbeat = lv_label_create(ui_SwitchUSBHeartbeat);
    lv_obj_set_width(ui_LabelUSBHeartbeat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUSBHeartbeat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUSBHeartbeat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUSBHeartbeat, "TX HeartBeat");

    uic_ScreenUSB = ui_ScreenUSB;
    uic_TextAreaUSB = ui_TextAreaUSB;
    uic_ButtonUSBStart = ui_ButtonUSBStart;
    uic_LabelUSBStart = ui_LabelUSBStart;
    uic_ButtonUSBStop = ui_ButtonUSBStop;
    uic_LabelUSBStop = ui_LabelUSBStop;
    uic_ButtonUSBSetting = ui_ButtonUSBSetting;
    uic_LabelUSBSettings = ui_LabelUSBSettings;
    uic_ButtonUSBExit = ui_ButtonUSBExit;
    uic_LabelUSBExit = ui_LabelUSBExit;
    uic_SwitchUSBHeartbeat = ui_SwitchUSBHeartbeat;
    uic_LabelUSBHeartbeat = ui_LabelUSBHeartbeat;

}

void ui_ScreenUSB_screen_destroy(void)
{
    if(ui_ScreenUSB) lv_obj_del(ui_ScreenUSB);

    // NULL screen variables
    uic_ScreenUSB = NULL;
    ui_ScreenUSB = NULL;
    uic_TextAreaUSB = NULL;
    ui_TextAreaUSB = NULL;
    uic_ButtonUSBStart = NULL;
    ui_ButtonUSBStart = NULL;
    uic_LabelUSBStart = NULL;
    ui_LabelUSBStart = NULL;
    uic_ButtonUSBStop = NULL;
    ui_ButtonUSBStop = NULL;
    uic_LabelUSBStop = NULL;
    ui_LabelUSBStop = NULL;
    uic_ButtonUSBSetting = NULL;
    ui_ButtonUSBSetting = NULL;
    uic_LabelUSBSettings = NULL;
    ui_LabelUSBSettings = NULL;
    uic_ButtonUSBExit = NULL;
    ui_ButtonUSBExit = NULL;
    uic_LabelUSBExit = NULL;
    ui_LabelUSBExit = NULL;
    uic_SwitchUSBHeartbeat = NULL;
    ui_SwitchUSBHeartbeat = NULL;
    uic_LabelUSBHeartbeat = NULL;
    ui_LabelUSBHeartbeat = NULL;

}
