// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: PowerController

#include "ui.h"
#include "esp_brookesia.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui_power_controller___initial_actions0;

// KEYBOARD
static lv_obj_t * kb = NULL;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_power_controller_init(void)
{
    ui_PowerController_screen_init();
    lv_disp_load_scr(ui_PowerController);
    ui_power_controller___initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_PowerController);
    ui_power_controller_setup_keyboard_events();
}

void ui_power_controller_destroy(void)
{
    // 销毁键盘如果存在
    if (kb != NULL) {
        lv_obj_del(kb);
        kb = NULL;
    }
}

void ui_power_controller___initial_actions_init()
{
}

void ui_power_controller_setup_keyboard_events(void)
{
    // Set up keyboard events for all text areas
    lv_obj_add_event_cb(ui_TextAreaADJVoltage, textarea_focus_cb, LV_EVENT_FOCUSED, NULL);
    lv_obj_add_event_cb(ui_TextAreaADJVoltage, textarea_focus_cb, LV_EVENT_DEFOCUSED, NULL);
    lv_obj_add_event_cb(ui_TextAreaADJCurrent, textarea_focus_cb, LV_EVENT_FOCUSED, NULL);
    lv_obj_add_event_cb(ui_TextAreaADJCurrent, textarea_focus_cb, LV_EVENT_DEFOCUSED, NULL);
}

void textarea_focus_cb(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * ta = lv_event_get_target(e);
    if (code == LV_EVENT_FOCUSED) {
        if (kb != NULL) return;

        kb = lv_keyboard_create(lv_scr_act());
        lv_keyboard_set_textarea(kb, ta);
        lv_obj_add_event_cb(kb, keyboard_ready_cb, LV_EVENT_READY, NULL);
        lv_obj_add_event_cb(kb, keyboard_ready_cb, LV_EVENT_CANCEL, NULL);
        
        // 优化键盘尺寸和位置 - 显示在输入框上方
        lv_obj_set_size(kb, LV_HOR_RES * 0.8, LV_VER_RES * 0.3);  // 键盘宽度80%，高度30%
        lv_obj_align_to(kb, ta, LV_ALIGN_OUT_TOP_MID, 0, -20);     // 相对于输入框，显示在上方，向上偏移20px
        
        lv_keyboard_set_mode(kb, LV_KEYBOARD_MODE_NUMBER);
        lv_obj_clear_flag(kb, LV_OBJ_FLAG_CLICK_FOCUSABLE);   /*To keep the text area focused on keyboard clicks*/
    }
    else if (code == LV_EVENT_DEFOCUSED) {
        if (kb != NULL) {
            lv_obj_del(kb);
            kb = NULL;
        }
    }
}

void keyboard_ready_cb(lv_event_t * e)
{
    lv_obj_del(kb);
    kb = NULL;
}
