// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: PowerController

#ifndef _POWERCONTROLLER_UI_H
#define _POWERCONTROLLER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "esp_brookesia.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_PowerController.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui_power_controller___initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_JetBrainsMono24);
LV_FONT_DECLARE(ui_font_JetBrainsMono36);
LV_FONT_DECLARE(ui_font_JetBrainsMono48);

// UI INIT
void ui_power_controller_init(void);
void ui_power_controller_destroy(void);

// KEYBOARD EVENT FUNCTIONS  
void ui_power_controller_setup_keyboard_events(void);
void textarea_focus_cb(lv_event_t * e);
void keyboard_ready_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
