// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UART TTL Debug Tool

#include "ui.h"
#include "esp_brookesia.h"

///////////////////// 变量定义 ////////////////////

// 事件相关变量
lv_obj_t * ui____initial_actions0;

// 图片和图片集

///////////////////// 测试LVGL设置 ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// 动画 ////////////////////

///////////////////// 函数 ////////////////////

///////////////////// 屏幕初始化 ////////////////////

void uart_ttl_ui_init(void)
{
    // 获取默认显示设备并设置主题
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    
    // 初始化所有屏幕
    ui_ScreenTTL_screen_init();
    ui_ScreenSettings_screen_init();
    
    // 创建初始动作对象
    ui____initial_actions0 = lv_obj_create(NULL);
    
    // 加载主屏幕
    lv_disp_load_scr(ui_ScreenTTL);
}

void ui_destroy(void)
{
    // 销毁所有屏幕
    ui_ScreenTTL_screen_destroy();
    ui_ScreenSettings_screen_destroy();
}
