// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: UART TTL Debug Tool

#ifndef _UART_TTL_UI_H
#define _UART_TTL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "esp_brookesia.h"
#include "ui_events.h"

///////////////////// 屏幕声明 ////////////////////

#include "screens/ui_ScreenTTL.h"
#include "screens/ui_ScreenSettings.h"

///////////////////// 变量声明 ////////////////////

// 事件相关变量
extern lv_obj_t * ui____initial_actions0;

// 字体声明
LV_FONT_DECLARE(ui_font_Number);

// UI初始化和销毁函数
void uart_ttl_ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
