// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Thermostat

#include "ui.h"

void onButtonStartClicked(lv_event_t * e)
{
	// Your code here
}

void onButtonStopClicked(lv_event_t * e)
{
	// Your code here
}
